### ISSUE TITLE
Shift + H doesnt work 

### ISSUE THREAD

**Issue by Locxion** [ArmaLife/Altis#100]
Hey Guys ... its me again ...
so i pulled the files from here and again Shift + H to Holster Weapon doesnt work.
Only modified file is the weapon shop ... thats clean now.
no error messages on client or server.

**Comment by danielstuart14** [comment]
@Heavybob

**Comment by Heavybob** [comment]
Yes?

**Comment by sargken** [comment]
Test @Heavybob

**Comment by Heavybob** [comment]
Need RPT errors. 

Running latest commit, no issues

**Comment by tkcjesse** [comment]
I run this as well. I have no issues?

**Comment by Locxion** [comment]
Sorry but i have no RPT errors on client or on the server :/ dont know why its not working.

**Comment by danielstuart14** [comment]
Maybe you changes something in keys on your game config.

**Comment by tkcjesse** [comment]
Is it holstering for you?

**Comment by Locxion** [comment]
@danielstuart14 fresh arma install ... completly on default

**Comment by tkcjesse** [comment]
@Locxion can you try this in your fn_keyHandler.sqf

http://pastebin.com/raw/Uhp8ZM5V

**Comment by Locxion** [comment]
paste complete?

**Comment by tkcjesse** [comment]
?? Just copy what I have in that pastebin and replace all of that file with that.

**Comment by Locxion** [comment]
no changes ... its the same file

**Comment by tkcjesse** [comment]
Yeah, there's just some proposed changes. Not sure if you were using those as well.

I would suggest seeing if you have custom actions assigned to H or Shift... Because that works fine on my server no issues.

**Comment by Locxion** [comment]
I will reinstall Arma again to make sure ... thanks anyway

**Comment by tkcjesse** [comment]
Just reset your controls?  Thats a bit extreme.  Making a new profile resets them.

**Comment by Locxion** [comment]
wow ... rage reinstall worked ... now i can holster my weapon -.- thanks.
i allready tryed to reset the keybindings and a new profile ... 
As a Thank you i completly Translated and fixed the german sections of the stringtables.xml ^^
