### ISSUE TITLE
Show amount of money on players HUD.

### ISSUE THREAD

**Issue by Kimax89** [ArmaLife/Altis#103]
I havent got the time to fully understand how everything works, so i wasnt able to add this myself.

This is a simple suggestion to add another element to the HUD that shows how much money you have in the bank and on you, so you dont allways have to check the usermenu.

I will try to look into this and if i succeed, i will add a pull request.

**Comment by tkcjesse** [comment]
Not sure if this is necessarily doable since we call hud_update to update the hud that currently exsists... I think it'd have to be changed around a bit?
I personally use a status bar. Which looks like http://www.exilemod.com/uploads/monthly_2015_09/2015-09-18_00010.jpg.b378d70f652fd44225ea6d26fe57d532.jpg

**Comment by Kimax89** [comment]
I will try to take a look at it anyway. In cases where people are using modded HUD, They will have to update that aswell.

But it would be a nice feature for the standart ui.hpp

**Comment by sargken** [comment]
I think the status bar way as @tkcjesse suggested would be a better route.

**Comment by tkcjesse** [comment]
Its super easy to add and remove things like adding wanted amount, players on the server, compass, etc. I like it.

**Comment by Kimax89** [comment]
is it a thing that could be added to the serverside?

**Comment by tkcjesse** [comment]
Its not a mod? You just add it to your Altis_Life.Altis

**Comment by Kimax89** [comment]
Why not add it, as a standard?

**Comment by tkcjesse** [comment]
the statusBar?  @Kimax89

**Comment by Kimax89** [comment]
yes. It has more functionality and looks better.

**Comment by Heavybob** [comment]
Doing this would mean that money checks would have to update hud each time a transaction is done. its possible to do but do we really want to make checks for money changes everywhere + remove the point of a player menu + annoy the kids more who don't have 1080p monitors? 

Just some thoughts.

**Comment by tkcjesse** [comment]
Doing the status bar doesn't require file calls everywhere like the current hud does. Not sure what dan wants to do.

**Comment by DarkSilencerZA** [comment]
I'd say status bar. Gives you flexibility with adding extras onto it and it's super easy to do.

**Comment by danielstuart14** [comment]
Not doing to happen, at least for now.
