### ISSUE TITLE
Cant repair Car. Error in Interaction Menu

### ISSUE THREAD

**Issue by Locxion** [ArmaLife/Altis#105]
If i look at a Vehicle and press Windows Key for Menu i get this Error.
 0:07:49 Error in expression <e;} else {_Btn6 ctrlEnable true;};
};
} else {

if(typeOf (_curTarget) in ["B_He>
 0:07:49   Error position: <else {

if(typeOf (_curTarget) in ["B_He>
 0:07:49   Error else: Type Array, expected code
 0:07:49 File mpmissions\__CUR_MP.Altis\core\vehicle\fn_vInteractionMenu.sqf, line 72
 0:08:23 Error in expression <e;} else {_Btn6 ctrlEnable true;};
};
} else {

if(typeOf (_curTarget) in ["B_He>
 0:08:23   Error position: <else {

if(typeOf (_curTarget) in ["B_He>
 0:08:23   Error else: Type Array, expected code
 0:08:23 File mpmissions\__CUR_MP.Altis\core\vehicle\fn_vInteractionMenu.sqf, line 72
 0:09:01 Error in expression <e;} else {_Btn6 ctrlEnable true;};
};
} else {

if(typeOf (_curTarget) in ["B_He>
 0:09:01   Error position: <else {

if(typeOf (_curTarget) in ["B_He>
 0:09:01   Error else: Type Array, expected code
 0:09:01 File mpmissions\__CUR_MP.Altis\core\vehicle\fn_vInteractionMenu.sqf, line 72

I and if its damaged i cant repair it.
my fn_vInteractionMenu.sqf: 
http://pastebin.com/6C2qEpnY
i didnt modify anything to this point

**Comment by danielstuart14** [comment]
Puff, people pushing broken commits... Will stop pushing until get home... Thx (latest release should work fine)

**Comment by tkcjesse** [comment]
@danielstuart14 beat me to it. 

Update yours with: http://pastebin.com/kh93ALGP

**Comment by tkcjesse** [comment]
@danielstuart14  Check again please? The current version has the issue still I believe, still has the kart/helicopter stuff... https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/vehicle/fn_vInteractionMenu.sqf

**Comment by Locxion** [comment]
great! worked perfekt! thanks!

**Comment by tkcjesse** [comment]
Did you use the paste or the current github?

**Comment by Locxion** [comment]
Your paste did the magic! The current file is broken

**Comment by danielstuart14** [comment]
Latest release in release tab

**Comment by danielstuart14** [comment]
Will take a look in the file (I'm on phone right now)

**Comment by danielstuart14** [comment]
@Shems-SA can you fix it? Your kart commit isn't working. I'm travelling and I can't edit it right now.

**Comment by tkcjesse** [comment]
The error seems to be probably this

 if(count crew _curTarget == 0 && {canMove _curTarget}) then { _Btn6 ctrlEnable false;} else {_Btn6 ctrlEnable true;};

You have ) in the wrong place i do believe. in a few spots.

**Comment by danielstuart14** [comment]
@tkcjesse if you can fix it I'll be glad

**Comment by Locxion** [comment]
@Danielstuart14 the paste from @tkcjesse worked great!

**Comment by tkcjesse** [comment]
Yeah, that's "old" if you will though. Doesn't have the gokart/heli commit submitted the other day.

**Comment by Shems-SA** [comment]
@danielstuart14 https://github.com/Shems-SA/Altis/commit/73222ce0155897ff3fcbe1ff3fd4c893c0c09e85 sorry for this problem :(

**Comment by Heavybob** [comment]
https://github.com/ArmaLife/Altis/pull/108

For the time been @Locxion, use this until its either reverted or fixed.

http://hastebin.com/fowitobupa.coffee

**Comment by Locxion** [comment]
@Heavybob like i said the pastebin (http://pastebin.com/kh93ALGP) from @tkcjesse worked fine for me.
Or should i use your files?

**Comment by tkcjesse** [comment]
@Locxion Use his if you want the Go-Kart enter / helicopter Enter on there. If not, using mine is fine. That's all mine didn't have.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/032bbf0c5987237c16d3ee519575c3c8eefa8e8d
