### ISSUE TITLE
Medic Put/Throw?

### ISSUE THREAD

**Issue by tkcjesse** [ArmaLife/Altis#110]
22:38:29 Duplicate weapon Throw detected for B_medic_F
22:38:29 Duplicate weapon Put detected for B_medic_F

Um... happened either when reviving or well... Not sure? Ideas?

**Comment by tkcjesse** [comment]
Possibly due to having the mediKit used with the disable medic weapon ability?

**Comment by Locxion** [comment]
Isn't there a "one-use" function? If you turn it on it will delete 1 item of your Inventar? And off it will stay there? Not Sure FirstAid Or Medikit

**Comment by tkcjesse** [comment]
Ah yes, could be... checking it out now. May have over reacted...

**Comment by danielstuart14** [comment]
that fixes the same spam in RPT for AGM: https://github.com/KoffeinFlummi/AGM/commit/c49c07ac3e30adb320511c7b6a0978015a938ebb

Going to take a deeper look later... But it's related (In AGM) to weapons not being removed on respawn, and then, being overrided.

**Comment by tkcjesse** [comment]
Yeah. It's part of a custom loadout file I'm using...
