### ISSUE TITLE
Vehicle Animation Error on spawning Cars

### ISSUE THREAD

**Issue by Locxion** [ArmaLife/Altis#115]
I'm getting this errors in Client log if i Spawn a Car. (Kavala Vehicle NPC)

Server log is clean.

extDB log:
17:31:14 "------------- Client Query Request -------------"
17:31:14 "QUERY: SELECT id, side, classname, type, pid, alive, active, plate, color FROM vehicles WHERE id='2' AND pid='76561198013153477'"
17:31:14 "Time to complete: 0.0187988 (in seconds)"
17:31:14 "Result: [2,"cop","C_Offroad_01_F","Car","76561198013153477",1,0,490765,8]"
17:31:14 "------------------------------------------------"
[17:31:14 +01:00] [Thread 18922] extDB2: SQL_RAW_V2: Trace: Input: UPDATE vehicles SET active='1' WHERE pid='76561198013153477' AND id='2'
[17:31:14 +01:00] [Thread 18922] extDB2: SQL_RAW_V2: Trace: Result: [1,[]]

Client log:
17:28:08 Suspending not allowed in this context
17:28:08 Error in expression < == "C_Offroad_01_F") then {
waitUntil {!isNil {_vehicle getVariable "Life_VEH_c>
17:28:08   Error position: <!isNil {_vehicle getVariable "Life_VEH_c>
17:28:08   Error Generic error in expression
17:28:08 File mpmissions\__CUR_MP.Altis\core\config\fn_vehicleAnimate.sqf, line 63
17:31:18 Suspending not allowed in this context
17:31:18 Error in expression < == "C_Offroad_01_F") then {
waitUntil {!isNil {_vehicle getVariable "Life_VEH_c>
17:31:18   Error position: <!isNil {_vehicle getVariable "Life_VEH_c>
17:31:18   Error Generic error in expression
17:31:18 File mpmissions\__CUR_MP.Altis\core\config\fn_vehicleAnimate.sqf, line 63

**Comment by Locxion** [comment]
The vehicle spawns without a problem ... forget to say this

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/8c478bdfd3400a551b8d1976c54d397b9de2a9cf
