### ISSUE TITLE
Error in Admin Menu if TP Player to Me

### ISSUE THREAD

**Issue by Locxion** [ArmaLife/Altis#116]
If i click on a Player and then the TP to Me Button I get this Error in Client log:

19:18:30 Wrong text element 'null'
19:18:30 Error in expression <prim,_sec,_attach,(_ret select 4),(_ret select 5),(_ret select 6)];>
19:18:30   Error position: <select 5),(_ret select 6)];>
19:18:30   Error Zero divisor
19:18:30 File mpmissions\__CUR_MP.Altis\core\admin\fn_admininfo.sqf, line 31

**Comment by tkcjesse** [comment]
Can you screencap the admin info for that user from the menu

**Comment by tkcjesse** [comment]
I have reason to believe this is due to how Tonic had his admin menu and the way it kinda forced me to do changes...

I think.. This is actually related to https://github.com/ArmaLife/Altis/issues/84 I believe.

**Comment by Locxion** [comment]
@tkcjesse 
Admin Menu: http://puu.sh/mNlod/e363a28571.jpg
Player Inventar: http://puu.sh/mNlCF/63302edd50.png
No Weapon No Attachments

**Comment by danielstuart14** [comment]
@tkcjesse I think it started to happen after your commit...
I'm going to test it and see what I can do

**Comment by danielstuart14** [comment]
it's related to players that don't have steamID. (Arma III retail)
Going to fix...

**Comment by tkcjesse** [comment]
Oh. That's silly.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/354a440766bc6c63ea08cd12b002ca3d15ef58ca should fix... Pls @Locxion , test it with your friend. (And ask him if he has a non steam game)

**Comment by Locxion** [comment]
Okay WE will try it if I get home. But I know he got it from steam like me. And if I click on my name I get the same error

**Comment by danielstuart14** [comment]
Then, IDK, because here it works just fine.

**Comment by sargken** [comment]
He may have an error on his local branch?

**Comment by Locxion** [comment]
@danielstuart14 http://puu.sh/mOie2/c38eb4f600.jpg ... its fixed! Thanks a lott!
