### ISSUE TITLE
Fishing loot Bug

### ISSUE THREAD

**Issue by Locxion** [ArmaLife/Altis#119]
If you use the fishing net addaction u get grilled fish instead of raw

http://puu.sh/mOmLB/9fd19ee96f.jpg

no errors on both sides

**Comment by tkcjesse** [comment]
@Locxion : Here ya go https://github.com/tkcjesse/Altis/commit/3c54aad7ae6b1cc7043ec8388bad95d4316adae8

**Comment by silvercn** [comment]
@tkcjesse what about Altis/Altis_Life.Altis/core/actions/fn_dropFishingNet.sqf? Looks like it needs to be also fixed if im not wrong

**Comment by tkcjesse** [comment]
@silvercn  Yeah I fixed that too, it was in there the whole time ;)
