### ISSUE TITLE
Error in fn_colorVehicle.sqf when spawning a vehicle

### ISSUE THREAD

**Issue by clackd1amond** [ArmaLife/Altis#13]
Seems, it doesn't affect anything, but it occurs everytime you spawn a vehicle.

RPT:
20:53:17 Suspending not allowed in this context
20:53:17 Error in expression <_VEH_color",_index,true];
};

waitUntil{!isNil {_vehicle getVariable "Life_VEH_c>
20:53:17   Error position: <!isNil {_vehicle getVariable "Life_VEH_c>
20:53:17 File mpmissions\__CUR_MP.Altis\core\vehicle\fn_colorVehicle.sqf, line 44

**Comment by danielstuart14** [comment]
yeah, I thought I fixed this... But seems that I didn't...

**Comment by crackhead** [comment]
I allredy gave a fix in the old get hub but you der it is no error there

**Comment by danielstuart14** [comment]
just pull-request it here

**Comment by Heavybob** [comment]
:+1: Pull request

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/c0f2aa748a1428334ee3fec6f469a78756db4fb0
