### ISSUE TITLE
Error in expression - fn_requestReceived.sqf

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#130]
The following appears in the client / local .rpt file at the spawn selection screen but before spawning into the game as a civilian. It does not occur when spawning as a cop/police or medic/ems. 

```
17:14:25 "::Life Client:: Waiting for the server to be ready.."
17:14:25 Error in expression <angData = (_this select 11);
if(!(count life_gangData isEqualTo 0)) then {
[] sp>
17:14:25   Error position: <life_gangData isEqualTo 0)) then {
[] sp>
17:14:25   Error Undefined variable in expression: life_gangdata
17:14:25 File mpmissions\__CUR_MP.Altis\core\session\fn_requestReceived.sqf, line 75
17:14:27 "Past Settings Init"
```

Spawning as police or medic for comparison.

```
17:17:11 "::Life Client:: Waiting for the server to be ready.."
17:17:43 "Past Settings Init"
```

Link to the file in question: [fn_requestReceived.sqf](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/session/fn_requestReceived.sqf#L75)

Full client / local .rpt available if needed.

Game version: 1.54.133741
Mission version: v4.3.3 - latest commit: 4eb14b6

**Comment by NiiRoZz** [comment]
Give me more information in server .rpt file you have any error ? And you are in a gang or you are not in a gang ?

**Comment by Jawshy** [comment]
@NiiRoZz, here is a link to the respective [server.rpt](http://puu.sh/mQqmY/8abb9ed125.rpt) file and I was not in a gang.

**Comment by danielstuart14** [comment]
Are you using this commit? https://github.com/ArmaLife/Altis/commit/044ce0299cb38cc57b6753c5d6fd4a8aecb1500a

Servers from before this commits needs a fresh database. (Or manual set of stats array)

**Comment by Jawshy** [comment]
@danielstuart14, no I am not. I will upgrade, refresh, and try again.

**Comment by NiiRoZz** [comment]
It's that because i have any error with the fresh database

**Comment by Jawshy** [comment]
No longer receiving this error after updating: 

- life_server
- @extDB2
- arma3life-4.0.sql

and starting with a completely new database. 

Closing...
