### ISSUE TITLE
Unsupported language English in stringtable

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#134]
The following message still appears in both the client / local.rpt and [server.rpt](http://puu.sh/mQqmY/8abb9ed125.rpt) despite \<English> being removed from the [stringtable.xml](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/stringtable.xml) as of commit a0dfdce71b6ba25e6453840d5eee3b3b447a034c. 

`20:44:46 Unsupported language English in stringtable`

I checked, double checked, and triple checked my stringtable.xml and mission .pbo and there is no \<English>. 

Game version: 1.54.133741
Mission version: v4.3.3 - latest commit: 4eb14b6

**Comment by danielstuart14** [comment]
Arma 3 being Arma 3...
Probably they set an English string in the game stringtable.
