### ISSUE TITLE
Storage crates disappearing from houses

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#137]
One storage crate will disappear from a player's house each time they disconnect and reconnect. None of the crates disappear from the database. How the creates disappear appears to go like this: 1, 2, 3, 4 → 1, 2, 3 → 1, 2 → etc.

Link to [.zip file](http://puu.sh/mQBAS/679949ccb5.zip) containing: 

- client/local.rpt
- server.rpt
- extDB log
- Database export of players and houses as an .xml

Game version: 1.54.133741
Mission version: v4.3.3 - latest commit: 4eb14b6

**Comment by NiiRoZz** [comment]
All time disconnect reconnect ?

**Comment by Jawshy** [comment]
@NiiRoZz, I reconnected several times and one storage crate would disappear everything. Also, the house I had was [**Land_i_House_Big_01_V2_F**](https://community.bistudio.com/wiki/Arma_3_CfgVehicles_EMPTY#Land_i_House_Big_01_V2_F) _House (Large, Yellow)_

**Comment by danielstuart14** [comment]
my idea to fix this, is redoing the whole house script.
Setting for each house an invisible supply box (Ex: Supply500)
It would be in the center of the house, and user would just need to scroll the mouse in it.

The good thing here, is that we doesn't need to handler with multiple crates anymore. Just one invisible box for each house.
Ex: Supply200, Supply300, Supply400, Supply450, Supply500

**Comment by NiiRoZz** [comment]
Jawshy you can test, you put 1 box you relog you see if box are here, if are here you put another and you relog, and just speak when box disappear. Thanks

**Comment by baua1310** [comment]
@danielstuart14 that's a very good idea

**Comment by Jawshy** [comment]
@NiiRoZz, here is what I did. 

Purchased House (Large, Yellow) → Placed small storage crate → Sync'ed and reconnected → Crate still there → Placed large storage crate → Sync'ed and reconnected → Crate still there → Placed another small storage crate →  Sync'ed and reconnected → Crate no longer there → Sync'ed and reconnected → 2nd small storage crate reappeared.

**Comment by Kimax89** [comment]
i had a similar problem, but i found out that 2 of the crates where stuck together. It was a bit tricky to access them both, but doable.

**Comment by Jawshy** [comment]
Just tested housing storage again and none of the crates disappeared. Same type of house but used large storage crate, then small, and small again. 

Also, moving items between inventory and storage was fine. Ref: #138 

Mission version: v4.3r4 - latest commit: f5e0e6895913ad4276607de228ba8af7ae42df97

**Comment by tkcjesse** [comment]
Yeah. The house storage thing was reported here...

https://github.com/ArmaLife/Altis/issues/138

Apparently it was "my files"... lol..
