### ISSUE TITLE
Storage Crates Inaccessible for Owner

### ISSUE THREAD

**Issue by tkcjesse** [ArmaLife/Altis#138]
So basically. If you are the owner of the house, you can only put magazines, suppressors, and nades in the crate. No clothes or anything. If you're not the owner you can put clothing and everything inside of it. You as the owner can also not remove anything once it's in their but others can..

I have a video I'll add shortly(Contains Profanity...). 
https://www.youtube.com/watch?v=wduZJxNMlBc

**Comment by danielstuart14** [comment]
I'm going to redo all the housing storage stuff.
Here, you can take a look in the idea: https://github.com/ArmaLife/Altis/issues/137

**Comment by tkcjesse** [comment]
Yeah, was looking to keep this method however. And just fix for the time being at least too.

**Comment by Kimax89** [comment]
Weird. I wasnt able to recreate the problem.

Where you using large or small containers?

Because i have only tested it with the large container.

**Comment by NiiRoZz** [comment]
I Will do New housse système With place yourself your container, and in database the container are séparate of house.

**Comment by tkcjesse** [comment]
It happens with both.. I'm going to try and bother with it today some.

**Comment by NiiRoZz** [comment]
I Will work on it need 2 days to do it, You will place where you want the container, but need in your house, save the position and content, and the storage will be locked by a code lock

**Comment by tkcjesse** [comment]
@Kimax89 Just downloaded the latest and greatest with no modifications, new database everything. Same issue persists with both crates.

**Comment by tkcjesse** [comment]
This is confirmed to be an issue in handleItem.sqf

Also, I don't have this interesting crate disappear bug in my older version from 4.1/4.2. Think this is new.. I shall compare.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/ffbfdc0d0b787d2e1653715819e06f198e2f04b0 fixes?

**Comment by tkcjesse** [comment]
I'll check it out.

**Comment by tkcjesse** [comment]
Did not fix... 

I'll pastebin what works. It was Yuka's old one... Theres like only 6 lines different though.

left out the macro on it..
https://gist.githubusercontent.com/tkcjesse/3fa163f3888170512adb/raw/0cc8cab5b158708aa5eb1e164da1c0b3a4ade162/gistfile1.txt

**Comment by NiiRoZz** [comment]
I think it's no a problem because i will do a new system and don't use handle item.

**Comment by danielstuart14** [comment]
I just checked it, and it's working...
Maybe you changed something in your files.
