### ISSUE TITLE
WARNING: Function 'name'

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#142]
The following messages are spammed in the local/client.rpt when reviving a civilian as a cop/police. 

```
21:22:14 WARNING: Function 'name' - MATTY is dead
```
```
21:22:16 WARNING: Function 'name' - civ_2 has no unit
21:22:16  - network id 2:1216
21:22:16  - person Athanasiadis
21:22:16  - dead
```

What I did was kill my test subject and then revive him as a cop. We then switched sides and did the same thing. Also a player that is revived losses their player tags (above their head). These message do not seem to appear if a civilian is revived by a medic/ems. 

Link to [.zip](http://puu.sh/mRLfK/28a0820033.zip) containing both the full client/local.rpt and the server.rpt

See also: #84 

Game version: 1.54.133741
Mission version: v4.3r4 - latest commit: c98c6409d2d86a0e58be3d381feb388a7b35b87f

**Comment by tkcjesse** [comment]
Further information: https://community.bistudio.com/wiki/name

See the notes at the bottom of that page. Need to modify how nametags work for dead bodies basically.

**Comment by Jawshy** [comment]
```
 0:02:17 WARNING: Function 'name' - 901ebc20# 1780566: pallet_milboxes_f.p3d REMOTE has no unit
 0:02:17  - network id 2:751
```

The above is incessantly spammed in the local/client.rpt after viewing the [Gang Armament crate](https://github.com/ArmaLife/Altis/issues/84#issuecomment-176322073) in a Gang Hideout up until disconnecting from the server.

**Comment by NiiRoZz** [comment]
I think it's in all getvariable real name, look this exemple : _cop GVAR ["realname",name _cop]; Use name Cop i think is that your spam.

**Comment by tkcjesse** [comment]
Yeah.

**Comment by danielstuart14** [comment]
@TAWTonic can you help us?

**Comment by danielstuart14** [comment]
Can you try these two commits?
https://github.com/ArmaLife/Altis/commit/e83cdd3f72327d742377bc63a21534d647ab9360
https://github.com/ArmaLife/Altis/commit/ec15a8c74746bbcd8fcef4e8fd4e0243ed6b0829

**Comment by tkcjesse** [comment]
Testing meow. Will just update this post. Not gonna make a new one.

**Comment by tkcjesse** [comment]
@danielstuart14  2 Issues..

First issue: I still get  
18:54:19 WARNING: Function 'name' - [BW]Cole. is dead

One of the keyhandler commits for the surrender causes Y menu to not open. Commenting out this, causes it to work fine..:

if((_code in (actionKeys "GetOver") || _code in (actionKeys "salute") || _code in (actionKeys "SitDown") || _code in (actionKeys "Throw") || _code in (actionKeys "GetIn") || _code in (actionKeys "GetOut") || _code in (actionKeys "Fire") || _code in (actionKeys "ReloadMagazine") || _code in [16,18]) && ({(player GVAR ["restrained",false])} || {(player GVAR ["playerSurrender",false])})) exitWith {
	true;
};

**Comment by danielstuart14** [comment]
About the warning, I have no idea then, as the script only runs if player is alive now.

About Y menu:
https://github.com/ArmaLife/Altis/commit/3f05d6c0acc3221d6816cda7f83a6c880c1f5f3d

**Comment by tkcjesse** [comment]
@danielstuart14   using        alive _x && {!isNil {_x GVAR "realname"}}   fixes it

**Comment by danielstuart14** [comment]
really? Can you test something for me then? (related to revive script)
I'm going to pull-request it

**Comment by tkcjesse** [comment]
Yeah. Sure

**Comment by danielstuart14** [comment]
@tkcjesse when you said that _x && {!isNil {_x GVAR "realname"}}  fixes it, are you talking about playerTags? Because it already checks for realname

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/ec0b60afea24a885d3252d49ec7598aae7bb5182
https://github.com/ArmaLife/Altis/commit/ec0b60afea24a885d3252d49ec7598aae7bb5182
