### ISSUE TITLE
Backpack required to buy rangermaster belt from gun store

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#144]
Players are required to be wearing a backpack in order to be able to buy a rangemaster belt from a gun store else they receive a message about not having enough space for the item. 

This does not affect buying vests from the rebel clothing shop (and presumably police clothing shop as well). 

Perhaps create a clothing shop for the gun store and move the belt into it? If so, could also do the same for the medics. 

Game version: 1.54.133741
Mission version: v4.3r4 - latest commit: c98c6409d2d86a0e58be3d381feb388a7b35b87f

**Comment by Jawshy** [comment]
Sometime today I will add in a separate clothing store for the gun shop, gang hideout, and medic store if someone else has not already started.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/1e19129ad80b2c01b6ba47bbe9b7bfbccad9ce57
