### ISSUE TITLE
Possible to rotate on the spot whilst restrained or surrendered

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#146]
It is a minor issue, but something to address none-the-less. 

It is possible for a player that is restrained or surrendered to rotate on the spot via SHIFT + Q or E. 

Game version: 1.54.133741
Mission version: v4.3r4 - latest commit: c98c6409d2d86a0e58be3d381feb388a7b35b87f

**Comment by danielstuart14** [comment]
idk if there's a easy way to do this. 
I'll do some research

**Comment by tkcjesse** [comment]
I have a solution for ya I believe.
I'll pull request if I do.

**Comment by tkcjesse** [comment]
@danielstuart14 the pull I did doesn't stop the Q + E movement. However it does stop things like vaulting, saluting, other stuff while in restraints that people commonly do to be funny or try inching away.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/69ff1efb87c100167843edea9a7ae189077ada51
https://github.com/ArmaLife/Altis/commit/672f27a9ecbe6af7623ed083d27d2b4f2af2a721
https://github.com/ArmaLife/Altis/commit/ea3a7d1e9be48b28c0ec92b6fdaf535c92fe338f
