### ISSUE TITLE
Squished shop/store menu

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#147]
There is insufficient space in the market menu and in other stores/shops to be able to fully display the names of items with long names. I suggest widening the menu so the names can be visible. 

###### Exhibit A
![Exhibit A](http://puu.sh/mRT5n/94043f1408.png)

Game version: 1.54.133741
Mission version: v4.3r4 - latest commit: c98c6409d2d86a0e58be3d381feb388a7b35b87f

**Comment by Jawshy** [comment]
_Bump._

**Comment by Liam0** [comment]
![107410_2016-02-18_00010](https://cloud.githubusercontent.com/assets/7563573/13147438/51755fa4-d659-11e5-8779-160a50f3f371.jpg)

Not perfect but it should help a little bit =)

**Comment by Jawshy** [comment]
@Liam0, think you could make it perfect? :)

![](http://puu.sh/nu39X/779e5e98ce.jpg)

**Comment by HyunsukBaek** [comment]
merge plz

**Comment by Kimax89** [comment]
Can someone close this, since it has been resolved and solution have been merged?

**Comment by Jawshy** [comment]
The "buy/sell item" buttons aren't centred.

**Comment by Kimax89** [comment]
oh okay.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/f60474c3da941f366a6e7c1bbae43d5583e99260
