### ISSUE TITLE
New fuel script

### ISSUE THREAD

**Issue by danielstuart14** [ArmaLife/Altis#149]
This is only for my brain memory, that is a crap.

- Things not working in the new fuel script / optimizations needed:
- Set the action if player is near to any pump. Not only the ones set in fn_Setup_Sation_Service
- Fix message after fuelling: "Vehicle is not near, bla bla bla"
- Don't open the menu if there isn't any vehicle near
- Only open the menu if the vehicle near is in life_vehicles or it's unlocked
- Start the default fuel amount in 1 liter, and disable the fuel bar if vehicle has less than 2 liters available for fuelling.

**Comment by NiiRoZz** [comment]
Ok i Will do all, but all pump are setuped because i use script juste copy
all the pump into array.

**Comment by silvercn** [comment]
Yeah also get an error when its refuled and try to fuel again.
[http://images.akamai.steamusercontent.com/ugc/364032107054880963/B842085B4F43693DBB6DE24E9146C2CD5A9B2B6A/](url)

**Comment by sargken** [comment]
Use the same detection as the ATM does. If you go up to an atm that doesn't have an addaction it will allow you to use interact with it and use the ATM.

**Comment by NiiRoZz** [comment]
@sargken It's impossible because i do setfuelascargo 0. If i dont setuped this in pump. Player can use arma 3 pump.

**Comment by NiiRoZz** [comment]
9fe8da05e3f7513d8b0accc3b7b4f9f45c6758de Fixed in this commits

**Comment by danielstuart14** [comment]
at least here it is auto-refuelling the vehicle
Maybe, we should let it as it was (arma auto-refuel), and let servers owners to implement if they want.

**Comment by danielstuart14** [comment]
will test now.
Let it open, there's some things that I'll do in the script and I need to remember.
