### ISSUE TITLE
New Housing System Issues

### ISSUE THREAD

**Issue by tkcjesse** [ArmaLife/Altis#153]
Current Issues (Updated - 2/7/16 9:17PM CST):

1. Testing the search, only thing left. Otherwise seems okay.

**Comment by danielstuart14** [comment]
@NiiRoZz about placing the crate outside the house, we can do a script to add a square marker (invisible) with the size of the house. If player is in it, he can place the crate

**Comment by NiiRoZz** [comment]
Yes i will fix all this bug.

**Comment by NiiRoZz** [comment]
For the 4 : i have tested and it's works for me
For the 5 : yes i know the little house ( non stone ), i don't place his classname in script i will.
For the 7 : 3 hours i will fix it
For the 3 : i will test this but i'm solo so i need time.
For the 1 : test with new commit but i will re code all this check i have idea.
For the 2 : i will check this so.

**Comment by NiiRoZz** [comment]
I have deleted the line when i fixed it.

**Comment by tkcjesse** [comment]
Alright @NiiRoZz, I'll update and check it out. Once again. Nice work.

**Comment by tkcjesse** [comment]
@NiiRoZz - Updated with recent found bugs.

**Comment by NiiRoZz** [comment]
@tkcjesse 66f9302015c9f07c5ad7e9e3e8eaf1eedfc25f10 You can test with this commits and update all your bug, i think will fix all new issues

**Comment by NiiRoZz** [comment]
@tkcjesse And for the 6 : Now i don't want because you need to the owner of the house.

**Comment by tkcjesse** [comment]
Alright, as I've said nice job. Issues were to be expected. I can't test out anything for like 12hrs though. I'll give feedback later when I add it!

**Comment by Jawshy** [comment]
A police search of a house with illegal items (drugs) finds nothing. (Using files as of 66f9302015c9f07c5ad7e9e3e8eaf1eedfc25f10)

**Comment by tkcjesse** [comment]
@Jawshy Even before searching crates had that issue. I'd suggest making a separate issue?

**Comment by NiiRoZz** [comment]
@tkcjesse test this commits pls for the 3 : ac81890aec66a23f3ea3dc7437382ef69b1de0e5

**Comment by tkcjesse** [comment]
@NiiRoZz  on it. I also added one more "issue"... not really an issue but would be nice to fix/change. Since crates are gone anyways.

**Comment by NiiRoZz** [comment]
For the 1 : enablesimulationglobal false so the crate passes through all

**Comment by NiiRoZz** [comment]
@tkcjesse For the 2 : It's impossible to fix, i use bounding box so it's in p3d model of house, so i can't fix it ... If player would place container just nearly house he can but crate can explode ...

**Comment by NiiRoZz** [comment]
@tkcjesse For the 5 : I do not understand. You would when you are in cop or medic you can acces in all house?

**Comment by tkcjesse** [comment]
Yeah, so if you own houses. And say you login as medic or cop, your crates aren't there but your house is still locked.

**Comment by NiiRoZz** [comment]
Ho ok if your house, you can acces, i will check this.

**Comment by tkcjesse** [comment]
@NiiRoZz ..  Sorry I think this only happens when you play civ first. Which locks them, but the doors don't become unlocked when you logout. That is probably a better way of saying it.

**Comment by NiiRoZz** [comment]
FOr the 3 : I have idea now police need check every container ( one per one ) and not the house

**Comment by tkcjesse** [comment]
@NiiRoZz  Also, when deleting storage, it doesn't update the value in the DB to allow the stored procedure to delete it. So if you delete them, when server restarts you still have your crates. Should be an easy fix.

**Comment by NiiRoZz** [comment]
@tkcjesse 7e14fef4b60e27cbf714127c5087af76edd809c3 test with this commit pls.

**Comment by tkcjesse** [comment]
@NiiRoZz using that commit it will delete multiple containers now if they're nearby. It was deleting them  before, just not updating the database to show them as deleted.

**Comment by tkcjesse** [comment]
Getting a bunch of : 
15:59:29 Bad conversion: scalar
15:59:29 Bad conversion: scalar
15:59:29 Bad conversion: scalar
15:59:29 Bad conversion: scalar
15:59:29 Bad conversion: scalar
15:59:29 Bad conversion: scalar
15:59:29 Bad conversion: scalar
15:59:29 Bad conversion: scalar
15:59:29 Bad conversion: scalar
15:59:29 Bad conversion: scalar
15:59:29 Bad conversion: scalar
15:59:29 Bad conversion: scalar

**Comment by NiiRoZz** [comment]
For the 3 : 52c61450176ee2960a8c1a03d85e857beb79bd6e

**Comment by NiiRoZz** [comment]
@tkcjesse For the 4 : I do not understand
For the 3 : I think that has fix
For the 2 : if you can explain more
For the 1 : i will do that soon

**Comment by Jawshy** [comment]
\4. Vehicle interaction menu is working for me as of ce81ef9. You need to have a toolkit in order to get the "Repair vehicle" option and sometimes the "Flip vehicle" options appears when the vehicle is upright and sometimes it does not appear. "Push boat" is fine.

**Comment by Jawshy** [comment]
1. Police/cop search of house does **not** find any illegal items (Example: drugs) but the database does detect that the item is in the container. Using: 63395af

 \5. Could not place down a large store container on the second floor of a [House (Large, Yellow)](https://community.bistudio.com/wiki/Arma_3_CfgVehicles_EMPTY#Land_i_House_Big_01_V2_F) \[need to test more]. 


Link to [.zip file](http://puu.sh/mXVI2/d370df52ec.zip) containing local/client and server.rpt logs, and database export of containers.

P.S. Could our messages here stop being deleted?

**Comment by tkcjesse** [comment]
Yeah same issue as @Jawshy, can't seem to place crates upstairs in buildings. Also, when selecting the crate and clicking use in the pmenu, the pmenu dialog should close once you hit use. I have an issue where a crate is now not doing anything and is actually stuck to me.

**Comment by NiiRoZz** [comment]
@Jawshy and @tkcjesse test this commits for can't place storage on 2nd floor in house : 7fd21dca6598f201259c264809febd22e8141ec7

**Comment by NiiRoZz** [comment]
@tkcjesse test and update all your issue

**Comment by tkcjesse** [comment]
Yeah, will do.  Out for the day.

**Comment by tkcjesse** [comment]
@NiiRoZz  Updated with recent issues.

**Comment by NiiRoZz** [comment]
FOr the 5 : i test all and for me, the crate delete every time
For the 6 : i test and for me, don't have 2 crate spawn
For the 2 : f8471ab0fa9a28b816cd854f483a073658c920df
For the 4 : yes you need to don't move and yes i know but is the best solution for check if you are in house ... This bug is most often in house doesn't have 2 floor;

**Comment by NiiRoZz** [comment]
Close because the last issue already define #182;
