### ISSUE TITLE
Police/cops can taze players inside of vehicles

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#158]
Police/cops can taze players that are inside of a vehicle, whether it is car, ship, or air. Car and ship require the tazer to hit the player whereas hitting anywhere on an air vehicle will taze the player. 

Relevant file(s): Altis/Altis_Life.Altis/core/functions/[fn_handleDamage.sqf](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/functions/fn_handleDamage.sqf)

Game version: 1.54.133741
Mission version: v4.3r4 - latest commit: 66f9302015c9f07c5ad7e9e3e8eaf1eedfc25f10

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/615e6068b7fda23e4d6949db240f11dc9cff4fb0
Should fix it & fix tazer in medics

**Comment by Jawshy** [comment]
@danielstuart14, tazers do not taze civilians at all.
