### ISSUE TITLE
Possible to enter/exit vehicles when restrained or surrendered

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#159]
It is possible for a player that is restrained or surrendered to be able to enter or exit an unlocked vehicle, and they can also use the interaction key to push boats or perform other actions when they should not be able to. 

Relevant file(s): Altis/Altis_Life.Altis/core/functions/[fn_keyHandler.sqf](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/functions/fn_keyHandler.sqf)

Game version: 1.54.133741
Mission version: v4.3r4 - latest commit: 66f9302015c9f07c5ad7e9e3e8eaf1eedfc25f10

**Comment by tkcjesse** [comment]
If they enter the vehicle though, doesn't it kick them out? Lines 56-59 on fn_restrain.sqf handle that...

**Comment by danielstuart14** [comment]
@tkcjesse only if they getIn as driver...

Afaik, we can't do that... This is because arma is dumb, and if we add a event handler preventing restrained players to getIn/getOut, cops will not be able to put/take players from vehicle.

**Comment by danielstuart14** [comment]
I have a idea... I'm going to pull-request it.
But I need someone to test before merging.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/pull/162
Just need someone to test (All possibilities: move to driver/get out in high speed/get out flying/etc)

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/3c2580fb08e8dc493f0ffa16feba3f9fd9b36cf3
