### ISSUE TITLE
ingame invite/rank promote for cop/medic || slot control

### ISSUE THREAD

**Issue by devShit** [ArmaLife/Altis#161]
cop/medic can invite civilian to join thier faction. it will be good experience for player after they passed the test. no need to manual update and be able to promote rank in game too

for slot chosing player should have only one faction to play if they are in cop they should not go on civ

i tink its not hard to create but should have on base system

**Comment by clackd1amond** [comment]
Yeah. It would also be cool if, for example, cops could give driving licenses to civilians. It would me the RP better, so civs won't be able to buy driver lincese, but will have to pass the test while the cops watches. And after the test, the cop desides wheather the civ can get license or not.

**Comment by sargken** [comment]
That would easily be abused also.

**Comment by CanadienFr** [comment]
This is very nice idea !

**Comment by Heavybob** [comment]
With my server, I am using a php script to promote people based on time played.

**Comment by Kimax89** [comment]
@Heavybob do you run that PHP with a cron-job or manually?

**Comment by Heavybob** [comment]
cron-job
