### ISSUE TITLE
Can Revive Anyone

### ISSUE THREAD

**Issue by tkcjesse** [ArmaLife/Altis#163]
As a medic you revive people who haven't even requested.

Assume this has to do with our actionKeyHandler checks? or fn_revivePlayer.sqf

**Comment by tkcjesse** [comment]
Line 66: actionKeyHandler also has  if(((playerSide == blufor &&    

Probably should change that to west.... haha.

**Comment by NiiRoZz** [comment]
Fix 52c61450176ee2960a8c1a03d85e857beb79bd6e

**Comment by tkcjesse** [comment]
This is still an issue. You can revive anyone even if they didn't request medic.
