### ISSUE TITLE
Text error when servicing a helicopter

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#165]
When servicing at Air Service Station. Screenshot below. ![this screenshot](http://puu.sh/mXQvv/a252c61ac5.jpg)

Related files: 
- Altis/Altis_Life.Altis/core/actions/[fn_serviceChopper.sqf](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/actions/fn_serviceChopper.sqf)
- Altis/Altis_Life.Altis/[stringtable.xml](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/stringtable.xml)

Game version: 1.54.133741
Mission version: v4.3r4 - latest commit: ce81ef9eb41e5121e53b1072ce5aeab30bcfef63

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/2a2e5671a4bbbef4729aa53d1f16dd7e925e3a65
