### ISSUE TITLE
Weapon Dupe

### ISSUE THREAD

**Issue by DarkSilencerZA** [ArmaLife/Altis#167]
When a player dies inside a vehicle, and the player is removed from the vehicle to be revived, the gun falls out of the vehicle onto the floor and does not get deleted.

Once the player is revived - he has a gun in his hands and a gun on the floor. (Duped)

**Comment by danielstuart14** [comment]
Can you try this?
https://github.com/ArmaLife/Altis/pull/173

**Comment by DarkSilencerZA** [comment]
I shall test and let you know.

**Comment by DarkSilencerZA** [comment]
Doesn't work.

**Comment by danielstuart14** [comment]
check this commit then :
https://github.com/danielstuart14/Altis/commit/e58347cdf309aa5a203d8ba68d3a9aea08f5b6b5

**Comment by DarkSilencerZA** [comment]
Will that work? From what I can see thats only when a player is revived. The issue we have is that it's not being deleted if the player is killed inside a vehicle and is pulled out.

**Comment by danielstuart14** [comment]
yeah, I think I found the issue
Check my pull-request again https://github.com/ArmaLife/Altis/pull/174

My question is, the weapon is dropped when player is pulled out or when he dies?

**Comment by DarkSilencerZA** [comment]
1. Player dies inside a vehicle
2. Player [dead body] gets pulled out of the vehicle
3. Player's weapon drops on the floor
4. Weapon is not deleted

**Comment by DarkSilencerZA** [comment]
The following is what happens:

1. Player dies normally
2. Player weapon drops
3. Player weapon gets deleted after a few seconds
4. Player gets revived
5. Weapon is returned to player

**Comment by DarkSilencerZA** [comment]
https://github.com/danielstuart14/Altis/commit/ed6ddd6f66cb7840d5b20dc5562537c1d4194ee0

This doesn't work. The weapon doesn't get deleted at all - even if the player is killed on the map.

**Comment by danielstuart14** [comment]
I see, so the problem isn't the delete weapon script.
It's just the pull out script that doesn't run it.

**Comment by DarkSilencerZA** [comment]
Correct

**Comment by NiiRoZz** [comment]
can fix but i don't know if work

**Comment by DarkSilencerZA** [comment]
I can test your fix for you

**Comment by NiiRoZz** [comment]
test this 2 commits :
https://github.com/NiiRoZz/Altis/commit/981080caddee633760b866038e90cee9d739fbd2
https://github.com/NiiRoZz/Altis/commit/ed4c0b25cb8ff1874fea3ff8214ade2ddfaf595d

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/4d8dd84c89ba86595e16b920597c3f70e5e23694

should work

**Comment by NiiRoZz** [comment]
No can't because you can pulout player not alive when for exmeple payer are death in driver if vehicle are unlocked just player go in driver the corpse of player will pullout

**Comment by danielstuart14** [comment]
yeah, but the weapon doesn't spawn in the floor when someone get in the place where the dead body was... At least I think

**Comment by NiiRoZz** [comment]
Fix : 41454c0e322254ebd9238eef4a5b1abdd5f49885

Only can execute on client i don't know why.
