### ISSUE TITLE
Civilian still restrained after cop/police disconnects

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#177]
When a cop/police restrains a civilian and then the cop dies the civilian is still restrained, **but** if the cop restrains a civilian and then disconnects to the lobby and from the server, the civilian remains restrained. 

Game version: 1.54.133741
Mission version: v4.3r4 - latest commit: 9bc8de6cb40491d0d1fd9ef6198edcb79f7e09b6 plus pulls #175 and #176

**Comment by danielstuart14** [comment]
try this: https://github.com/ArmaLife/Altis/commit/e8f7c9dd1f7de340e2560d18e32637acfc71dee8

**Comment by tkcjesse** [comment]
@Jawshy

Players should become un-restrained after 5 minutes when they have no cops near them (30 meters)

@danielstuart14 
if(isNull _cop) exitWith {
		player SVAR ["Escorting",false,true];
		detach player;
};

Did NOT work for me. I had the restraining cop disconnect and the player remained restrained.

**Comment by danielstuart14** [comment]
yeah, I'll let how it's for now.
