### ISSUE TITLE
Turning Player arround in Clothingshop

### ISSUE THREAD

**Issue by silvercn** [ArmaLife/Altis#178]
Would be great if you could get a slider on the Clothingshop, so that you can turn the player arround, and see also the backside.

**Comment by danielstuart14** [comment]
I like the idea. It isn't that hard to do...
(How could I never thought about that, awesome idea)

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/28dcc7760fec2c98655c16bb07f64e40b0d4376f
