### ISSUE TITLE
Smallbox: remove container

### ISSUE THREAD

**Issue by danielstuart14** [ArmaLife/Altis#180]
Smallbox (ammobox_f or Box_IND_Grenades_F) only shows the interaction menu if player is proned

**Comment by tkcjesse** [comment]
Yeah. Noticed with the large crate too. Its pretty hard to get the dialog. Maybe an addaction to delete would be better?

**Comment by danielstuart14** [comment]
currentTarget is better, I think

**Comment by NiiRoZz** [comment]
You cant cursortarget, you are in house and i dont want to use nearestobjects because spam of bad conversion scalar in rpt

**Comment by NiiRoZz** [comment]
Cursortarget will return all the time the house, don't return the container ..

**Comment by tkcjesse** [comment]
Ah...

**Comment by NiiRoZz** [comment]
Fix : 780a2a8127b3f210c2ec39de922205b21e80c616
