### ISSUE TITLE
House issue 

### ISSUE THREAD

**Issue by danielstuart14** [ArmaLife/Altis#181]
Sometimes player's houses just disappear. (They still in DB and are shown as owned, but player can't open it or spawn on it.)

To "solve this", player has to buy a new house and disconnect, Then, all the houses show up.

I'm working on it, but if someone has an idea, I'll be glad.

**Comment by devShit** [comment]
ya experience about this in other case. so
some time like you said instead. other player find a buyable house and that house actually have the owner but. they can still buy it even the owner standing in front of the door (while i test that)

and i write a query to check it if any house have more than one owner
`select a.pos , a.id
from (select * from houses where pos not in (select pos from houses group by pos having count(pid) = 1))
a
left join (
  select ma.pos, min(ma.id) as id
        from (
            select h.pos, h.id
            from houses h
            inner join (
                select pos 
                from houses 
                group by pos 
                having count(pid) > 1) t
            on h.pos = t.pos
        ) ma 
        group by ma.pos
) dup
on a.pos = dup.pos and a.id = dup.id
where dup.pos is null or dup.id is null`

and yes the prove is alot of house shown in result. in that time i using 3.1.4.8 with 800 rows in house table

**Comment by NiiRoZz** [comment]
If anyone can reply me why not use init house just one time : select all house and setvariable, why use inner join because you need to wait player join to addvariable locked to the house, why didn't select all house and setup the variable in house, just don't use INNER JOIN use just select and where in all house. I don't know if are a nice idea.

**Comment by devShit** [comment]
i agree with you NiiRoZz

**Comment by NiiRoZz** [comment]
Test this and look if the issue persist : 1c65fb05c27bcd0fd45e4ed4304ec0fa617d7ac4

**Comment by danielstuart14** [comment]
after this commit, it doesn't even work.
No rpt error

**Comment by danielstuart14** [comment]
Showing any house now. 
No rpt errors

**Comment by devShit** [comment]
it should setup all house when server start up when player is joined. isn't it ?

**Comment by NiiRoZz** [comment]
Now setup all house when server start, if you setup when player join, anyone can buy house of other player and you have multiple orner in house.

**Comment by NiiRoZz** [comment]
I have setup and my house showed up, all my house and have variable house owhere.

**Comment by devShit** [comment]
no no i mean i should setup all before player join in that is

**Comment by NiiRoZz** [comment]
With my commit, he setup all before join, he don't use INNER JOIN
