### ISSUE TITLE
Crate / Vehicle Searching Issues

### ISSUE THREAD

**Issue by tkcjesse** [ArmaLife/Altis#182]
Returns no illegal items if the sellPrice is set to -1. This happens on unprocessed stuff mostly. Including bolt cutters / charges

**Comment by NiiRoZz** [comment]
Fixed : bc1f73f715469e374afe594389e49e9abecf683e

**Comment by tkcjesse** [comment]
Says that "Nothing Illegal Inside", even though there is. Also checked vItems to make sure the item was marked "illegal = true".

**Comment by NiiRoZz** [comment]
I will recheck because me i have tested only vehicle and it's work, i will recheck and update

**Comment by tkcjesse** [comment]
Okay. It could be me possibly..... My files match though...

**Comment by NiiRoZz** [comment]
I have retested before leave my house and for me it's work for vehicle, it's said have illegal but i think the sellprice are bugged.

**Comment by tkcjesse** [comment]
Okay. Must be something on my side. I'll try it again later.

**Comment by tkcjesse** [comment]
@NiiRoZz So the problem is.... when the sellPrice is -1, it won't be found...

**Comment by NiiRoZz** [comment]
Yes i Will rework the system tomorrow.

**Comment by tkcjesse** [comment]
Well otherwise we can just make it so illegal items have sell prices?

**Comment by NiiRoZz** [comment]
I will just when are a item unprocessed just check thie price of item processed, just that.

**Comment by NiiRoZz** [comment]
Test this : 2adcb91fbeeace634b4d417a1bb991ac6915a907

**Comment by NiiRoZz** [comment]
2a079baa533d839a86a6bef55d9db069bbf909d3 this fix

**Comment by tkcjesse** [comment]
I think dan wanted to still use the pocessedItem though. According to last nights gitter conversation.

**Comment by NiiRoZz** [comment]
It's impossible blastingcharge don't have processed item, if you create item only for price it's very ...
