### ISSUE TITLE
Wanted System Issues

### ISSUE THREAD

**Issue by tkcjesse** [ArmaLife/Altis#183]
1. fn_wantedProfUpdate was added but isn't used anywhere?

**Comment by NiiRoZz** [comment]
Men all your issue, i have test With @danielstuart14 and all work, only the 4 i didn't test

**Comment by tkcjesse** [comment]
@NiiRoZz I would double check you committed everything? As there was no Strings and such. Unless you tested it without text on the buttons?

**Comment by NiiRoZz** [comment]
Ho sorry men yes i dont modify directly this version so i dont put cfgremoteexec i Will do, @tkcjesse sorry men

**Comment by NiiRoZz** [comment]
I Will do in 9 h ours because i can't do Now

**Comment by tkcjesse** [comment]
No problem man. I'm sure it came off rude. Just got frustrated with how you seemed to have worded that. Didn't mean it rude, we all make mistakes :)

**Comment by NiiRoZz** [comment]
I'm just frustred because when i work on it i search in all file error Just i don't put "=" in query but i search this error 30 times.

**Comment by NiiRoZz** [comment]
But when i test all work, just i don't test when multiple player are inside the wanted liste.

**Comment by tkcjesse** [comment]
Yeah. The two fixes I posted, I know the first one works, where it just grabs everyone. As I added that a little bit ago and it works fine now. The 2nd fix by AlaskaVet, I'm not sure. haven't tried. 

https://i.gyazo.com/acdc6c504beb2028a62e3baf5b5477e3.png

If you need me to host it or anything and I'm on, I'm more than willing!

**Comment by NiiRoZz** [comment]
Your fix it's don't need because i check if are anything in array units and if fond anything Just pushback, i have alreadJust already fixed it, i think.

**Comment by NiiRoZz** [comment]
You fin de any error other the cfgremoteexec ?

**Comment by NiiRoZz** [comment]
Wanted add work ?

**Comment by tkcjesse** [comment]
I didn't implement any of the changes I suggest beyond the solution for #4. I perfer to change things as they're commited. Otherwise I make mistakes/forget things easily -_-    Trying to basically do 3 Altis Lifes at once. Haha

**Comment by NiiRoZz** [comment]
Test with this version : 01e2ab7025cfa8b43dae3ac21df87e1bca24a449

**Comment by tkcjesse** [comment]
@NiiRoZz   Wanted list shows when only 1 civ is wanted. When another user is on that's currently wanted, the list doesn't work.

https://i.gyazo.com/28869fce7c972afcb2cf2427c3404c7d.png

**Comment by tkcjesse** [comment]
It has to do with how sql adds "\" I believe. Something with the wantedFetch statement method...

**Comment by cammygames** [comment]
@tkcjesse try this for wantedFetch. http://pastebin.com/K3mV4jjR I have this code working on my server

**Comment by danielstuart14** [comment]
@tkcjesse 
https://github.com/ArmaLife/Altis/commit/07149fb6d8df47b6fd819c1fdc78079cbf3e11f2

Can you try if it is renaming the player after he change the name?

**Comment by tkcjesse** [comment]
Will do in a bit

**Comment by tkcjesse** [comment]
Fixed.
