### ISSUE TITLE
Vehicles have thermals after retrieving from garage

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#185]
Buying a vehicle from a shop will [disable the vehicle's thermal imaging](https://community.bistudio.com/wiki/disableTIEquipment) upon spawning, but retrieving a vehicle from the garage does not have this check. 

Relevant files: 
- Altis/Altis_Life.Altis/core/shops/[fn_vehicleShopBuy.sqf](https://github.com/ArmaLife/Altis/blob/7ded6071294f0fc5c1cec6a2e21221d592db423a/Altis_Life.Altis/core/shops/fn_vehicleShopBuy.sqf)
- Altis/Altis_Life.Altis/dialog/function/[fn_unimpound.sqf](https://github.com/ArmaLife/Altis/blob/f01dabb49191de7ee4acb6475af110784e295ba7/Altis_Life.Altis/dialog/function/fn_unimpound.sqf)

Game version: 1.54.133741
Mission version: v4.3r4 - latest commit: d22eee001dc4f1bad912814f5d8327f75ad9fccc

**Comment by NiiRoZz** [comment]
I Will fix it when i return in my home

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/9153290368bf2faa649572e87477810e1b33fb15
