### ISSUE TITLE
New HUD clips through default Arma HUD elements

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#193]
I suggest the [custom HUD](https://github.com/ArmaLife/Altis/commit/0666382f983c2f059c016705e62681d6cad43a7d) be moved down to the bottom. 

###### Custom HUD
![](http://puu.sh/n1pon/a878043943.jpg)

Game version: 1.54.133741
Mission version: v4.3r4 - latest commit: 0523f59c2210650884559a874d50ba1c1de8c617

**Comment by DarkSilencerZA** [comment]
Yeah move it down to bottom.

**Comment by Heavybob** [comment]
Agreed, game ruined because of hud. Completely unplayable.

*Just kidding around, looks a bit funky, not a big issue*

**Comment by sargken** [comment]
^^

**Comment by danielstuart14** [comment]
Will set it at bottom as default and add an option for setting at top

**Comment by sargken** [comment]
Sweet

**Comment by Jawshy** [comment]
9df38ef7e5061c220418dbcf9bf4f0535b424111
/closed
