### ISSUE TITLE
Diamond mine not working

### ISSUE THREAD

**Issue by Kimax89** [ArmaLife/Altis#206]
all i get is "You not near a mine"

I have checked the marker in the mission file, but no luck there.
And i cant figure out where the zones are defined.

I'm not that familiar with the structure so i'm kinda looking around blindfolded.

**Comment by sargken** [comment]
Can you get the name of the marker.

**Comment by Kimax89** [comment]
class Item34
		{
			position[]={18478.988,25.055317,14297.403};
			name="diamond_mine";
			text="@STR_MAR_Diamond_Mine";
			type="mil_triangle";
			colorName="ColorBrown";
		};

**Comment by sargken** [comment]
Is there a zone around it highlighted? Ex diamond_1

**Comment by sargken** [comment]
It looks for the zone, if there isn't make a circle and name it that.

**Comment by Kimax89** [comment]
there is only diamond_mine

I will change that to diamond_1 and see if that works.
i can see that the iron mine is named iron_1

**Comment by Jawshy** [comment]
I'll make a pull request momentarily.

**Comment by sargken** [comment]
thanks @Jawshy

**Comment by Kimax89** [comment]
that worked. Gonna pull that right away.

**Comment by Jawshy** [comment]
Issue can be closed.
