### ISSUE TITLE
Remove all traces of my work

### ISSUE THREAD

**Issue by Itsyuka** [ArmaLife/Altis#207]
I want any file that was created and/or modified by me to be removed completely.

Reason: Removing credits.

**Comment by sargken** [comment]
https://github.com/ArmaLife/Altis/blob/b6b281db803eb1fed03690df943fd12e55736388/Altis_Life.Altis/core/cop/fn_copLoadout.sqf

**Comment by sargken** [comment]
https://github.com/ArmaLife/Altis/blob/b6b281db803eb1fed03690df943fd12e55736388/Altis_Life.Altis/core/functions/fn_saveGear.sqf

**Comment by sargken** [comment]
That's what comes up when I type in your name.

**Comment by Itsyuka** [comment]
And modified, don't forget modified. (70% of altis-life I believe)

**Comment by killerty69** [comment]
I am pretty sure he means all his commits.

**Comment by danielstuart14** [comment]
Didn't even touch the header of files I changed.
Only HUD I changed, and that was because I redid about 99%.

I really would understand if someone had merged a script you did without your permission, but all your scripts here were you who merged. Again, the only one was HUD, and I'm pretty sure I already mentioned it.

So, if you can point any file your credits were removed, pls, just show me. otherwise, there isn't nothing to blame.

I'm really not understanding this, is that some kind of rage?

**Comment by tkcjesse** [comment]
@Itsyuka -> https://github.com/ArmaLife/Altis/commits?author=Itsyuka

I just randomly opened a bunch of those... No where in there do you ever modify the header to include yourself... Feel free to find some files where you did...

**Comment by Itsyuka** [comment]
Nah, still want stuff removed, I wanted to make a stupid reason

**Comment by tkcjesse** [comment]
@Itsyuka Ah yes! Because you willingly pushed shit to a public repo that mind you was Tonic's... Go ask Tonic to do it...

**Comment by danielstuart14** [comment]
Okay, you want, that's pretty awesome.
But I think you didn't read the license that Altis-Life is covered, and it was before you start working on it.

Sorry mate, if you want it to be remove, talk with tonic.

**Comment by Kimax89** [comment]
@Itsyuka You cant just give out cookies to strangers and later demand to get them back. Thats not how a public repo works.

**Comment by Itsyuka** [comment]
"If in any case that content is being used within this mission / framework that the content creator doesn’t wish for it to be used due to my strict TOA / Agreement all you need to do is ask for it to be removed and it will be honored. "

**Comment by sargken** [comment]
Who says it will be honored?

**Comment by sargken** [comment]
Tonic and who's around now?

**Comment by TAWTonic** [comment]
That refers to peoples work that was not added by them, it does not include yourself that you willing did.

**Comment by Itsyuka** [comment]
@TAWTonic Was dared to say it, and I never cared about the crap work I did.

**Comment by Arkensor** [comment]
Wow such Kindergarten ... public github repo = I do not care about other people using my content / I want other people to use my content.

Nothing more, nothing less. Dunno why you complain @Itsyuka ... they want to work with altis life, so let them do ;)

**Comment by chris579** [comment]
However, you still have your copyright and your're able to define who is allowed to use your code. Doesn't matters what shitty license is covering this.

**Comment by danielstuart14** [comment]
this isn't how things work...

You should take a look in GPL, MIT and even CC license.

Think about if Linus, out of the blue, decides that anyone could use his linux sources anymore.
Or even, if an ext4 developer decides that anyone could use their ext4 sources.
Many projects would be ruined (Android, canonical, redhat, MANY banks, etc). And this is why, open-source licenses exist. Preventing any child to fuck a project up because their mad with someone.

**Comment by chris579** [comment]
You should keep in mind that there was never a CC license or something like that. It was the own license + disclaimer. So, rekt.
Altis Life never had an open source license.

**Comment by danielstuart14** [comment]
Really? This is one of the first commits Tonic did: 
github.com/ArmaLife/Altis/blob/188919639914c50801b4a022f8a27739b46caf31/README.md

Read the first lines pls, and stop posting lies here. If you don't know something, just don't say anything.

**Comment by chris579** [comment]
If you're an idiot just stop writing here either,

**Comment by Arkensor** [comment]
@chris579 did you just Rekt yourself ? *lol*

**Comment by chris579** [comment]
@Arkensor Did you just Rekt your life? *lol*

**Comment by Arkensor** [comment]
@chris579 well no. I was not the one, getting the fail of the year award .. BTW how are the wind turbine doing. Still a performance issue ?

**Comment by devShit** [comment]
@Arkensor tell people how to host 200 player

**Comment by Arkensor** [comment]
@devShit ok: if(performace == "bad") then {performace = "good"}; done. And remove all wind turbines from the map, as @chris579 found out they would cost much performace, because of the non existent network sync. *lol*

**Comment by falkebo** [comment]
@devShit tell people how to write unnecessary comments...

**Comment by chris579** [comment]
@Arkensor how is it to be a faggot? Wondering that you are still living. I hope you send Yawalla another time to us, we're happy about a bit flaming from an pseudo sovereign server admin. However, wish you best luck with an Altis Life server without roleplay and with still bad performance. Hope you can fap on your 200 players that make your penis 1.2 inces longer. PS: Remove your 7 script threads in your mission. This is a real performance lack. And not such shit as "Get near players".

**Comment by Arkensor** [comment]
@chris579 ok godfather. You are so right, how dare we are to host 222 players ... I will split it into 2 hives with 80 players, and make my mission as shitty as youre one ist. That must the the true altis life feeling ... Sad that you are still butthurt.

Enjoy your little but 100% roleplay server, with this awesome performace. And its pretty cool that you still look up our mission, to copy the ideas on your server.

I am sorry that I thought I would know how to deal with such a large server, I will give you all files and let you do the magic, to achive the true altis life feeling.

@Moderator remove my comments, It's a bit mean to offend this kid, as he needs to defend himself, even though he knows that he is wrong in everything he says. That makes me feel bad :(

**Comment by chris579** [comment]
@Arkensor Funny that you still think that there are things in your mission other could steal. You don't have any features. Funny kid.

**Comment by devShit** [comment]
@chris579 why real altis life server won't host more than 100 are you joking to me its very fun

**Comment by chris579** [comment]
@devShit Because it ends in an RDM party and shitty performance.

**Comment by Arkensor** [comment]
@chris579 Oh yeah you already took all ideas, indeed sorry for that. Now you are taking my word KID to offend me, how clever. Much Wow.

Look where you and your server are, and then look where I am ... and then think about who's concept might be better

**Comment by devShit** [comment]
i hosting full of 90 player and its already RDM party no different of slot amount its depend on how you control i tot

**Comment by chris579** [comment]
@Arkensor Still, your server has no ideas and no features I could even took. And your hyper Mikero protection is also stopping me from looking into your hyper optimized shit mission. I don't care about a Gametracker rank. As I can see you do. So, have fun with your shitty server. And you're still a bad developer. Have fun with your further life.

**Comment by Arkensor** [comment]
@chris579 have fun, with your server too. Yeah If I am rank .. I dont know something bad, cause I dont see pirates anywhere on the first pages - then I would call on ranks either. 

yes I am such a bad developer, as Ive stated you should get all the files and share you perfect scripting knowledge with us, sir. 

That you know about our protection, means you at least tried it once ahahah

Have fun with your further life.

**Comment by sargken** [comment]
@chris579 Get the fuck off this chat.

**Comment by sargken** [comment]
@chris579 go get stuck up further @Itsyuka ass. Because he was "dared" im sure.

**Comment by tkcjesse** [comment]
@Arkensor @chris579 if you guys have things to express, do it on the altisliferpg.com forums. Here's not the place for this crap.
