### ISSUE TITLE
Bail Guy

### ISSUE THREAD

**Issue by Heavybob** [ArmaLife/Altis#211]
How does one pay bail without NPC?

**Comment by danielstuart14** [comment]
if you remove the NPC from its group it shows up.
Idk why... I think just creating another solve the problem. Will test out

**Comment by TAWTonic** [comment]
It's because his formation is not set to None, its set to follow or w/e so he is teleporting to the master_group NPC.

**Comment by sargken** [comment]
@TAWTonic You getting back in to Altis Life?

**Comment by TAWTonic** [comment]
No i'm just answering a fairly easy question.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/f386941f92676c1d3b17464a44e6bc99db2df14b

Thx tonic, never thought about that.
