### ISSUE TITLE
Suggestion: multiprocess

### ISSUE THREAD

**Issue by clackd1amond** [ArmaLife/Altis#219]
Combine 'x' items of 'a'-resource and 'y' items of 'b'-resource and get 'z' items of 'c'-resource. The main idea is set here: http://www.altisliferpg.com/topic/9820-script-dynprocess-by-ryan/, but I don't think that automatically buying a license without proposal and info about the license price is a good idea.

**Comment by NiiRoZz** [comment]
You you have all the time very fucking idea ;)

**Comment by clackd1amond** [comment]
I'm sorry, my English is not very well. "very fucking idea" - is it good or bad?
Cause I've got plenty of them :)

**Comment by NiiRoZz** [comment]
Good but hard ;)

**Comment by clackd1amond** [comment]
Yeah, Ryan's scripts are good,but a bit out of date

**Comment by chris579** [comment]
Ryans scripts are not good. This is crap. You have to hardcode the required items on the map. Don't use it!

**Comment by clackd1amond** [comment]
That's why I suggested of creating more convenient script. I know it can be done but I'm not very good at it: (

**Comment by Heavybob** [comment]
I was tempted to running ryans dynamic market though I was going to use a php script to adjust the values for each item. Thinking outside the box but it would work.

**Comment by sargken** [comment]
@chris579 since your a master fucken coder you do it for your self. Dont cut on someone elses shit.

**Comment by chris579** [comment]
I did. And I'm happy with my code since it is perfect.

**Comment by sargken** [comment]
Then Stop Bitching, since your such a master coder.

**Comment by tkcjesse** [comment]
Please stop arguing in chat. Use private chat in gitter or go to the forums with it...

**Comment by DarkSilencerZA** [comment]
It's a good idea. I am currently running a similar idea on my server. Not Ryan's stuff though. It's our own.

**Comment by NiiRoZz** [comment]
#229

**Comment by NiiRoZz** [comment]
72bb0425c76488ef7b33319523cbaa61e6d57138
