### ISSUE TITLE
Player Position Save & Market system with ExtDB 

### ISSUE THREAD

**Issue by magicianaos** [ArmaLife/Altis#224]

**Comment by magicianaos** [comment]
How about player position save & market save system?

**Comment by sargken** [comment]
How would it be a market save system.

**Comment by magicianaos** [comment]
just like below link
http://www.altisliferpg.com/topic/4833-tutorial-sql-based-market-dynamic-economy/#comment-31487

**Comment by sargken** [comment]
http://www.altisliferpg.com/topic/9971-script-dynamicmarket-by-ryan-altislife-3148-and-4000-compatible/? That you mean?

**Comment by magicianaos** [comment]
Yes, I think ExtDB market system batter than current market system.

**Comment by sargken** [comment]
I think so also, the script can use some improvement.

**Comment by danielstuart14** [comment]
player position is going to be added soon... I'm finishing it.

dynamic market won't be added, at least for now.
