### ISSUE TITLE
life_server\fn_updateGang.sqf Error

### ISSUE THREAD

**Issue by magicianaos** [ArmaLife/Altis#228]
rpt log file error message

Error in expression <Members","_members","_query","_owner"];
params [
["_mode",0,[0]],
["_group",grpN>
  Error position: <params [
["_mode",0,[0]],
["_group",grpN>
  Error Params: Type Group, expected Array
File life_server\Functions\Gangs\fn_updateGang.sqf, line 9

**Comment by NiiRoZz** [comment]
When ?

**Comment by magicianaos** [comment]
when I create a gang.
Maybe.

**Comment by NiiRoZz** [comment]
we need more precision about this error.
She knows reproduced from?
the precise moment it happens please.

**Comment by danielstuart14** [comment]
Are you with the latest version and with vanilla gang system?

Because, the error says: Error Params: Type Group, expected Array

BUT any of the params expect an array. _mode expect a number, and _group expect a group

**Comment by magicianaos** [comment]
Yes I use current file & vanillia gang system

Um...I'll check.

**Comment by danielstuart14** [comment]
Going to reopen after OP gives a RPT log.

Here I can't reproduce it.
