### ISSUE TITLE
Scroll ---> Seize Items (Cops)

### ISSUE THREAD

**Issue by DarkSilencerZA** [ArmaLife/Altis#230]
A good feature to add would be for a cop to have the ability to scroll ---> Seize any weapons / items etc that's on the ground or even on another player.

**Comment by danielstuart14** [comment]
cop interaction (windows key) would be better

**Comment by sargken** [comment]
I like the action instead because Windows key menu half the time doesn't work when picking up money

**Comment by Heavybob** [comment]
I have never had an issue using the windows key on a user. Money is defined server side so thats why its not always perfect. If this could be done and check what weapons are in the rebel shop / any other illegal shops to mark as illegal, this could work perfectly.

**Comment by Heavybob** [comment]
Same thing with clothing found in rebel shops

**Comment by sargken** [comment]
Money is not done server side its done in key handler. Its done a shitty way by doing cursortarget.

**Comment by DarkSilencerZA** [comment]
Remember that this doesn't just include a player. This could be a weapon that's dropped on the ground by another player (not by death).

**Comment by NiiRoZz** [comment]
If you don't want use cursorTarget so use nearestObject, look animals now use this. OS if you want you can use nearestobjects

**Comment by MrHeavyMetal** [comment]
This would be cool if it did infact check what was available at the rebel shop to define illegal items but if items had to be added manually then it could be a pain in the ass

**Comment by DarkSilencerZA** [comment]
Nah - just a general "Seize Items". Doesn't have to be specific. There can be a check when scrolling on a restrained player to remove a weapon. Otherwise anything on the ground can be seized (deleted).

**Comment by TravisPrice** [comment]
http://www.altisliferpg.com/topic/13539-tutorial-seize-weapons-script/

**Comment by HyunsukBaek** [comment]
good

**Comment by dardothemaster** [comment]
Or maybe[ this ](http://www.altisliferpg.com/topic/12229-3148-release-search-seize-for-cops/)

**Comment by DarkSilencerZA** [comment]
No, use this: http://www.altisliferpg.com/topic/13539-tutorial-seize-weapons-script/#comment-82983

It works, I'm using it on 4.4.2 (live server).

**Comment by tkcjesse** [comment]
I'll be doing both a ground seizure and also off persons. Expect it in a few hours.

**Comment by tkcjesse** [comment]
Player Item Seize -> https://github.com/ArmaLife/Altis/pull/459
