### ISSUE TITLE
Housing Bug

### ISSUE THREAD

**Issue by DarkSilencerZA** [ArmaLife/Altis#231]
1. Player buys house
2. Player spends lots of money populating house
3. Server restarts
4. Player can spawn at house but cannot do anything inside house
5. When player presses Windows Key it gives the option for a player to buy the house again

16:04:10 Error Max array size would be reached. Current size: 993183, wanted size: 1003422.
16:04:10 File life_server\Functions\MySQL\fn_asyncCall.sqf, line 36
16:04:10 Error in expression <p = false}; _queryResult = _queryResult + _pipe; }; } else { if (!(_queryResult >
16:04:10 Error position: <+ _pipe;
};
} else {
if (!(_queryResult >

@NiiRoZz says that he knows about this issue. Not sure why we went onto a stable build with this issue. It's literally game breaking.

**Comment by NiiRoZz** [comment]
72bb0425c76488ef7b33319523cbaa61e6d57138
