### ISSUE TITLE
Health Problems in Altis

### ISSUE THREAD

**Issue by Heavybob** [ArmaLife/Altis#232]
Everyone knows that to stay alive in altis you need food and water. 
I propose, what happens to the food and water after you consume it?
Do we just bloat up and become crazy inflated people? 

I propose an actual toilet system. 
![](http://i.imgur.com/PQp60P1.jpg)

Lets try to shit this one out together guys.

**Comment by DarkSilencerZA** [comment]
LOL epic!

**Comment by Kimax89** [comment]
thats could be a great idea. Will i be able to shit in the bushes?

**Comment by danielstuart14** [comment]
noop

**Comment by Jawshy** [comment]
> :( My poop suggestion was flushed

@Heavybob, circa 2016.
