### ISSUE TITLE
Veh Config Overhall Suggestion

### ISSUE THREAD

**Issue by Heavybob** [ArmaLife/Altis#233]
Prices for veh should be automatically defined like this to make everything fair regarding prices.

VItemWeight (User Defined) + Armor + Fuel Capacity x Horsepower = Price of Rental Price x veh_prices (in master config)
(this won't work for armed so I would suggest to exempt them)
Chopshop = 50% of Rental Price of Veh x veh_prices (in master config)
Insurance = 30% of Rental Price of Veh x veh_prices (in master config)

then to adjust for economys of servers, in the master config
veh_prices = 5 (so all the end results will be times by 5. You could make this zero but if its too high then you could alternatively divide the amount *not really required*)

Doing this will take out at least 3 lines of code for each veh in the veh_config. 
I did the math, system could work.

**Comment by DarkSilencerZA** [comment]
I think it's a good idea. Saves a shit ton of time sorting out pricing and what not when starting a server. Makes things easy to manage.

**Comment by sargken** [comment]
I dont like the idea, I would want to set vehicle prices manually. But the idea to have them be dynamically picked for chopshop and insurance is good.

**Comment by danielstuart14** [comment]
actually, you would be able to set it as auto, just removing the price and setting "auto" in the place

**Comment by Heavybob** [comment]
My proposal is designed to be manual but make it extremely easy for price setting. 
You still have to define the vitem space for the veh and on that data will calculate the price.

**Comment by sargken** [comment]
But that makes no since to be because your still not setting the price.

**Comment by Heavybob** [comment]
The price is calculated via the method. 

Lets say I had a Ural with x space


200 vitem space + 140 + 12 x 80 =  28160 x Mulitplyer x 10 = 281600 
VItemWeight + Armor + Fuel Capacity x Horsepower = Price of Rental Price x veh_multiplyer

**Comment by sargken** [comment]
No thanks.

**Comment by DarkSilencerZA** [comment]
No thanks? So if you had 60 + vehicles (example) - you'd want to go and do all of that stuff manually? Do you like wasting time? Because I don't. It's way better to have it automated with the exception of you being able to change them manually if need be to adjust for your economy.

**Comment by Heavybob** [comment]
VItemWeight + Passanger Capacity + Armor + Fuel Capacity x Horsepower = Price of Rental Price x veh_multiplyer

**Comment by sargken** [comment]
I like doing it my self so I can set the prices. So I said no thanks, I would go set them manually and ill continue to do it. Its called setting up your economy for your server, now you can say your multiplier in the config is there for that but I dont see it that way. Its my opinion no need to attack me over it.

**Comment by MrHeavyMetal** [comment]
I think this would make a cool Opt-In feature, Add the ability to have prices Auto-configure for those that want it and leave manual editing as the default, pleases both sides.

**Comment by NiiRoZz** [comment]
Closed already inside of mission, if you want to don't use it, modify you're mission
