### ISSUE TITLE
should we have a GUI show trunk item info while player on it ?

### ISSUE THREAD

**Issue by devShit** [ArmaLife/Altis#236]
inspire of server crash no matter what reasons.
player can take a shot before accept that session lost dialog.
so administrators can give back some money.
i don't know if you guys have situation like me so.

**Comment by devShit** [comment]
![12742786_10208854188054303_6272187856415037974_n](https://cloud.githubusercontent.com/assets/16807706/13068322/cbdcaddc-d4ac-11e5-92ad-12190fdb6cc1.jpg)

**Comment by Kimax89** [comment]
thats why it would be nice to have everything in the database ;)

Some might say that it would be causing problem if there is too much data, but i actually dont see that as problem.

**Comment by NiiRoZz** [comment]
It's impossible, it's in engine of arma, you can't delete session lost, if you see Session Lost, the mission are not running so can do anything, just go to a server don't crash ;)

**Comment by Jawshy** [comment]
> just go to a server [that doesn't] crash ;)

This.
