### ISSUE TITLE
Error in expression - fn_cleanupRequest

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#238]
The following appears in the server.rpt file when a player (with default/spawn loadout) aborts to the lobby. 

```
2016/02/16, 20:39:08 Bad conversion: array
2016/02/16, 20:39:08 Error in expression <alive _client) exitWith {
_containers = nearestObjects[_client,["WeaponHolderSim>
2016/02/16, 20:39:08   Error position: <nearestObjects[_client,["WeaponHolderSim>
2016/02/16, 20:39:08   Error 0 elements provided, 3 expected
2016/02/16, 20:39:08 File life_server\Functions\Systems\fn_cleanupRequest.sqf, line 18
```

Relevant file(s): Altis/life_server/Functions/Systems/[fn_cleanupRequest.sqf](https://github.com/ArmaLife/Altis/blob/master/life_server/Functions/Systems/fn_cleanupRequest.sqf)

Full .rpt files available on request.

Game version: 1.54.133741
Mission version: v4.4r1 - latest commit: 77176f6c27b4be8c4ef76f09a8ccc144a760a560

**Comment by NiiRoZz** [comment]
The unit are alive or not ?

**Comment by Jawshy** [comment]
The player was alive when aborting to the lobby.

**Comment by NiiRoZz** [comment]
Fixed https://github.com/ArmaLife/Altis/commit/cb0b70d8f125242c7962003d33a85eea732c98c3
