### ISSUE TITLE
Gang Bug

### ISSUE THREAD

**Issue by crackhead** [ArmaLife/Altis#24]
Leaving a gang error
3:40:30 Error in expression <eGroup civilian);

[_unit,group player] remoteExec ["TON_fnc_clientGangLeft",_un>
23:40:30   Error position: <remoteExec ["TON_fnc_clientGangLeft",_un>
23:40:30   Error Typ Jede, erwartet Zahl, Seite, Objekt, Gruppe, Zeichenfolge
23:40:30 File mpmissions\__CUR_MP.Altis\core\gangs\fn_gangLeave.sqf, line 17
23:47:30 Fresnel n must be >0, given n=0,k=10

**Comment by danielstuart14** [comment]
Should fix: https://github.com/ArmaLife/Altis/commit/bc2ab196ca9f054bd0c1b0ed50f9a159ad95f9bf

Give a feedback pls
