### ISSUE TITLE
Don't save resource items for persistent vehicle inventory

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#240]
Only [virtual items that cannot be abused](https://github.com/ArmaLife/Altis/blob/b6b281db803eb1fed03690df943fd12e55736388/Altis_Life.Altis/core/functions/fn_saveGear.sqf#L141-L142) can [be set as persistent](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/Config_Master.hpp#L10) for players' inventories. So why then are [vehicle inventories](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/Config_Master.hpp#L12) persistent for all virtual items?

**Comment by danielstuart14** [comment]
yeah, you're right. I was going to do that, but I forgot

**Comment by magicianaos** [comment]
You can find fn_saveGear.sqf

Line 140

> } forEach [
	"pickaxe","fuelEmpty","fuelFull", "spikeStrip", "lockpick", "defuseKit","storageSmall","storageBig","redgull","coffee","waterBottle","apple","peach","tbacon","donuts",
	"rabbit","rabbitRaw","salema","salemaRaw","ornate","ornateRaw","mackerel","mackerelRaw","tuna","tunaRaw","mullet","mulletRaw","catshark","catsharkRaw","turtleSoup","turtleRaw","hen","henRaw","rooster","roosterRaw","sheep","sheepRaw","goat","goatRaw","goldBar","blastingCharge","boltCutter","oilUnprocessed","oilProcessed","copperUnrefined","copperRefined","ironUnrefined","ironRefined","saltUnrefined","saltRefined","sand","glass","diamondUncut","diamondCut","rock","cement",
	"heroinUnprocessed","heroinProcessed","cannabis","marijuana","cocaineUnprocessed","cocaineProcessed"
];

**Comment by sargken** [comment]
Or make it an option for servers to choose what they want?

**Comment by NiiRoZz** [comment]
Added : c866f7bf4257bbfadbfbcfbdf65281af7d56375a

**Comment by HyunsukBaek** [comment]
@magicianaos  e662b78

I confused about "_" <-- this characters. 
According to lastest version of files, 
there are defined "turtle_raw" as class name included "_" in Config_vItems.hpp. 
and save_veh_items[] in Config_Master.hpp also used as class name for each y items. 

which name do you use ?
