### ISSUE TITLE
Separate Money of Ticket with all cop on duty

### ISSUE THREAD

**Issue by CanadienFr** [ArmaLife/Altis#242]
I have another suggestion when a cop give a ticket to a player and he pay just separate all the money with the officers on duty or when the cops find drug or contraband stuff in the car or player.

**Comment by Heavybob** [comment]
That sounds like a good idea. Should do the same with impounding too.

**Comment by NiiRoZz** [comment]
Good Idea but if you give a ticket of 1000 $ and have 10 cop it's very very very ;;;;

**Comment by ColinM9991** [comment]
$2 with 10 cops :stuck_out_tongue_closed_eyes:

**Comment by NiiRoZz** [comment]
I think it's a good idea if disable when the tickect < 30000 and after enable auto

**Comment by CanadienFr** [comment]
Generally a tickets it between 1000 to 50000$ depend on the server. He have no problems with 1000$ = 100$ each cops it good :+1:

**Comment by CanadienFr** [comment]
@NiiRoZz Yeah it good idea !

**Comment by devShit** [comment]
$1000(or somemore) per cop, no matter on how much ticket is.(for decrease global money)

**Comment by NiiRoZz** [comment]
04cf5b20b3742391ca1b442d3ce9a6e6c40c9c77
