### ISSUE TITLE
life_fnc_MP Problem

### ISSUE THREAD

**Issue by magicianaos** [ArmaLife/Altis#250]
Since then removing life_fnc_MP. Old script does not work 4.4 life version. 
Please tell me what the script cope with life_fnc_MP.

Don't work script
For example
1) `[[player],"TON_fnc_getActions",false,false] spawn life_fnc_mp;`

2) `[[player,"Acts_BoatAttacked01"],"life_fnc_animSync",true,false] spawn life_fnc_MP;`

**Comment by NiiRoZz** [comment]
It's your script or in the main mission ?

If it's your mission, change life_fnc_mp to remoteexec
spawn life_fnc_MP; = remoteExec
call life_fnc_MP ; = remoteExecCall

**Comment by magicianaos** [comment]
1) - My life server motion key.

2) - Life server Admin tool Ryan version..

**Comment by NiiRoZz** [comment]
You need your own change life_fnc_mp to remoteexec look commit when change.

**Comment by magicianaos** [comment]
Thanks for you help

**Comment by NiiRoZz** [comment]
#251 Thanks @ColinM9991
