### ISSUE TITLE
Battle Eye Filters - More Testers

### ISSUE THREAD

**Issue by Heavybob** [ArmaLife/Altis#254]
Hiya guys, 

With the additions of more data regarding battle eye filters myself and others who are working around with the new filters are experiencing some really pesky kick reasons. I have been going though and writing down some of them but only with the combined effort of people testing the new filters will it become better.

Shift + P DLC Purchase Menu
Scripts.log:
http://hastebin.com/hodesuweni.md

Backpack Purchase 
Create Veh Log:
http://hastebin.com/risefisucu.css

Open Debug Console
Scripts.log:
http://hastebin.com/tanafujika.1c

**Comment by Jawshy** [comment]
I will make a pull request patching the BEFilters with these and other fixes momentarily.

**Comment by Jawshy** [comment]
#255 

> Backpack Purchase 
Create Veh Log:
http://hastebin.com/risefisucu.css

Isn't fixed because `B_Bergen_blk` is already part of an exception. Double check that your [createVehicle.txt](https://github.com/ArmaLife/Altis/blob/master/BEFilters/createVehicle.txt) is up-to-date. It should have `!B_Bergen_` somewhere.

**Comment by Heavybob** [comment]
Will check.

**Comment by Heavybob** [comment]
Scripts.Log:
http://hastebin.com/pacamiyeso.css

**Comment by Heavybob** [comment]
Knockout / Rob Set Variable Kick:
http://hastebin.com/iyokudiwut.coffee

**Comment by Heavybob** [comment]
Opening a new issue page.
