### ISSUE TITLE
Include this storage system [suggestion]

### ISSUE THREAD

**Issue by MrHeavyMetal** [ArmaLife/Altis#256]
http://www.altisliferpg.com/topic/13280-custom-house-inventory-system-replacing-boxes/

I think this is a better system than the boxes, perhaps limit it by number of items

**Comment by tkcjesse** [comment]
@MrHeavyMetal I had actually brought this up to @danielstuart14 a while back. This was his response: https://i.gyazo.com/488828fd5bdc41774dc127c589127ba4.png   Basically using the Arma UI for inventory is a better solution.
