### ISSUE TITLE
ADAC

### ISSUE THREAD

**Issue by Actione** [ArmaLife/Altis#266]
ENG (Google translator);
could you would kick it in OPFOR adac nice not get out the
thank you
mfg
actione_xd

GER
könntest du in OPFOR adac reinmachen wäre nett bekomm das nicht hin
danke 
mfg 
actione_xd

**Comment by sargken** [comment]
So what do you want?

**Comment by baua1310** [comment]
He wants you to build in opfor as standard with the function of a roadside assistance, the so called ADAC in Germany. Although there are tutorials, he isn't able to get this working.

**Comment by NiiRoZz** [comment]
For me this feature should not be in main build

**Comment by baua1310** [comment]
@NiiRoZz I go along with you

**Comment by Actione** [comment]
could make me one with the data request

**Comment by midgetgrimm** [comment]
you could make it a config setting with the basis of you MUST add the npc and player units as a serverowner. easy to edit the civ files to include east, but if they want an entire system, then no they should be on their own

**Comment by Angrygargamel** [comment]
c'mon guys... this is LIFE... we have cops and medics... why shouldnt we have a technical service too?
also this is the most requested stuff from people i know... and by far not the easiest to achieve...

if this could be implemented by default and with an on/off option in the cfg
or better said: if you add the playercharacters of the side east you have them... if not then not...

**Comment by danielstuart14** [comment]
it's possible, but it isn't a feature that we're going to add in the next commits...
The problem is that, these sided sides (he he he), like medics, isn't used most of the time... No one wants to cross the whole map just for reviving someone.
