### ISSUE TITLE
[Suggestion] Vehicle store timeout

### ISSUE THREAD

**Issue by clackd1amond** [ArmaLife/Altis#267]
Since we save vehicle inventory, it can be abused easily. You can transfer your items from one end of Altis to another by stroring your car to garage, relogging to another town and unimpounding your car there. Fast and safe. My suggestion is to add a timeout for stored vehicle, so when you store it, it will appear in your garage after 15-20 minutes.

**Comment by NiiRoZz** [comment]
Abusé for what ? All ressource doesn't save in véhicle.

**Comment by clackd1amond** [comment]
Weapons, for example

**Comment by NiiRoZz** [comment]
Ok i will put this 10 minutes

**Comment by clackd1amond** [comment]
Thank you

**Comment by NiiRoZz** [comment]
4dcbbfd8b1977ac45d7fe2579673c5f82ea67997
