### ISSUE TITLE
Medic Lights

### ISSUE THREAD

**Issue by numpty9989** [ArmaLife/Altis#271]
Medic Lights dont  (cops work fine) work no errors in rpt stock mission file... also great work so far guys

**Comment by NiiRoZz** [comment]
I Will fix it in 1 hour, just wait this time and it's fixed.

**Comment by numpty9989** [comment]
ok cheers

**Comment by numpty9989** [comment]
also instead of making a new issue are you able to look at question dealer as i fet this error too https://gyazo.com/7275897304eb0326b275e19b95722873

**Comment by NiiRoZz** [comment]
I Will check it

**Comment by numpty9989** [comment]
and if poss i know im asking a lot on one issue post but cannot capture hideouts (no option) if you have time n cheers for help

**Comment by NiiRoZz** [comment]
All hideouts ?

**Comment by numpty9989** [comment]
just tested hideout 2

**Comment by numpty9989** [comment]
am checking others now

**Comment by numpty9989** [comment]
all of them
the poles have code butt just dont want to work

**Comment by numpty9989** [comment]
nvm bout gang hideouts my bad id just created gang n wouldnt let me take area xD that works

**Comment by numpty9989** [comment]
it hadn't synced my gang to DB

**Comment by NiiRoZz** [comment]
For me lights medic work.

**Comment by numpty9989** [comment]
hmm ok i know beacons work but the siren lights dnt like the cop car lights

**Comment by NiiRoZz** [comment]
Fixed sorry : 3df7ea08de24f56bd9cb78fff3abf51517a09953
