### ISSUE TITLE
Vehicle & Boat garage error

### ISSUE THREAD

**Issue by magicianaos** [ArmaLife/Altis#273]
Air garage is working good.

Vehicle & boat garage, stored in garage is work's fine.

But, When I try to take out the car it does not come back to this list.

DB save is work's fine. maybe garage bug exist

p.s I'm using vanilla version

**Comment by NiiRoZz** [comment]
You use véh save gear ?

**Comment by magicianaos** [comment]
Yes. my Config_Master.hpp config
save_veh_gear = true;
Is that problem?

**Comment by NiiRoZz** [comment]
Yes, when you have items in your vehicle you need to wait 20 minutes for the vehicle to be in your garage

**Comment by NiiRoZz** [comment]
But i will code a message now

**Comment by magicianaos** [comment]
I got it.

Thanks for your answer. :)

**Comment by NiiRoZz** [comment]
1f92851e564ab22b9eea27f3e7ac6216748276a3
a6989e6ac71e2d75a476123cfdeafc63f9c08d63

**Comment by magicianaos** [comment]
Thanks~!!
