### ISSUE TITLE
clothing_box Errors / Box Bug

### ISSUE THREAD

**Issue by Heavybob** [ArmaLife/Altis#29]
https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/shops/fn_clothingMenu.sqf

clothing_box = false;
Silent Errors. 

Client RPT Logs:
http://hastebin.com/hofowatufu.tex

clothing_box = true;
Missing a wall from the box.

**Comment by danielstuart14** [comment]
fixed?

**Comment by Heavybob** [comment]
testing, sec

**Comment by sargken** [comment]
No i need to move the testlogic out of the if statement.

**Comment by danielstuart14** [comment]
okay. Remember to test out things before pushing, next time...

**Comment by sargken** [comment]
There are 2 errors in there tomarrow i will post a fix.

**Comment by Heavybob** [comment]
Checking errors, if they are minor, I will fix

**Comment by danielstuart14** [comment]
Guys, look. 
I was taking a look on these commits, and they are a mess.
It is calling UpdateInventory every time player opens trunk, and it isn't formated as the whole script is.

Also, clothing changes aren't working.

So, I'll revert they. My advice is: Do a repo, with these changes. (One for clothing changes, and other for vehicle), then, I'll look and test it. (And if needed fix what is broken.) 
After this, then, I'll merge it here...

We can let the official repo broken, this is why I pushed my commits to here, instead still using my own profile.

**Comment by sargken** [comment]
Since this isnt a release so people should be downloading things strait from the repo therr should be a release there downloading from. Vehicle Gear Virt Item save is working well now. Clothing shop has a minor bug on it which can be fixed easly. The reason i push to this is so heavy can test. Is there a way you can allow me to tag a tag WIP to my pull requests so you know there not ready to go.

**Comment by sargken** [comment]
I wrote that from my phone so sorry for some grammar mistakes.

**Comment by danielstuart14** [comment]
Remember that scripts don't just need to work, but it needs to respect the syntax and be optimized for better FPS.
The commit you pull-requested calls for vehicle inventory on DB every time player opens the trunk...
So, it overhead the sv.

As I said before, push it to your repo and comment on issue tab.

As I'm on vacation, in the same day you push it, I'll test and give my opinion...

**Comment by sargken** [comment]
Im wondering if we even need it im going to look more into it to it.

**Comment by danielstuart14** [comment]
It just needs to call for database when storing or spawning from/to garage.
If you want I can fix it, but not in this repo.

I know how boring it is, but as there's only one branch here, we can't break it.

**Comment by sargken** [comment]
I think what im going to do is name things im working on - WIP when its initially done then i can pass it onto heavybob. Once its all checked out then ill tagg you in it and let you know. Would you be good with that? Im on phone sry if there are grammar errors.

**Comment by danielstuart14** [comment]
I think it's better to just push to your repo. (With branch-naming, like: vehicle_persist)
Then, send it to me.

It's better for large commits... Pull-request mess everything up, and give a chance to push non-working features.

Small changes can still being pull-requested.

As I said before, send me your email (Everybody) and I'll create a hangouts chat with everybody.
It's easier for me to reply. (Just opening gmail you are ready to chat.)
