### ISSUE TITLE
AltisLife.sql - Database Error

### ISSUE THREAD

**Issue by Locknlol** [ArmaLife/Altis#295]
Error
SQL query:

DELIMITER ; -- -------------------------------------------------------- -- -- Table structure for table `players` -- CREATE TABLE IF NOT EXISTS `players` ( `uid` int(12) NOT NULL AUTO_INCREMENT, `name` varchar(32) NOT NULL, `aliases` text NOT NULL, `playerid` varchar(50) NOT NULL, `cash` int(100) NOT NULL DEFAULT '0', `bankacc` int(100) NOT NULL DEFAULT '0', `coplevel` enum('0','1','2','3','4','5','6','7') NOT NULL DEFAULT '0', `mediclevel` enum('0','1','2','3','4','5') NOT NULL DEFAULT '0', `civ_licenses` text NOT NULL, `cop_licenses` text NOT NULL, `med_licenses` text NOT NULL, `civ_gear` text NOT NULL, `cop_gear` text NOT NULL, `med_gear` text NOT NULL, `civ_stats` varchar(21) NOT NULL DEFAULT '"[100,100,0]"', `cop_stats` varchar(21) NOT NULL DEFAULT '"[100,100,0]"', `med_stats` varchar(21) NOT NULL DEFAULT '"[100,100,0]"', `arrested` tinyint(1) NOT NULL DEFAULT '0', `adminlevel` enum('0','1','2','3','4','5') NOT NULL DEFAULT '0', `donato[...]

MySQL said: Documentation

#1293 - Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

**Comment by Heavybob** [comment]
You are clearly not importing the database properly...

**Comment by sargken** [comment]
Line 177 of sql file needs to be updated to CREATE TABLE IF NOT EXISTS `wanted` (

**Comment by Locknlol** [comment]
@sargken Same error persists.

**Comment by Locknlol** [comment]
@Heavybob Doing it the same way I installed 4.3 and that worked just fine.

**Comment by N1colas62** [comment]
Same here, i'm in MySQL 5.6

**Comment by danielstuart14** [comment]
Try it now, after @NiiRoZz's commit: 6d01da9d2334c373b5297bd94ef1b2b757ac3e08

**Comment by sargken** [comment]
You can thank me ;)
