### ISSUE TITLE
Vehicle preview (suggestion)

### ISSUE THREAD

**Issue by Heavybob** [ArmaLife/Altis#3]
*REPOST FROM PREVIOUS GIT*
https://github.com/danielstuart14/Altis-Life/issues/53

@clackd1amond 
Sometimes new players that don't have a lot of money on them want to see what they buy. They see clothes but they don't see vehicles. Is it possible to create for veh shop a similar preview mode as for the clothes? It would be very helpful and would look awesome.

@danielstuart14 
yes, we can do it as clothing shop.
Create a box that spawns the car.

@clackd1amond 
Can't wait for this, thank you! :)

**Comment by NiiRoZz** [comment]
75b507ad5001ddc6dbd170c06c1885dedaa9502c
