### ISSUE TITLE
[Question] Eden editor issue

### ISSUE THREAD

**Issue by magicianaos** [ArmaLife/Altis#303]
Use Eden edtior, my modified life missions file. 

But can not anymore read mission file. 

Anymore it does not support old mission files from Eden?

**Comment by Kimax89** [comment]
AltisLife is not supported with the new mission format in the Eden Update.

If you wish to modify the mission file, you can still use the old 2D editor.

**Comment by MrHeavyMetal** [comment]
I have not had an issue updating the mission file to the Eden Editor, also is there any plans to support the Eden Editor by default? 

If i remember correctly the original editor is getting fazed out in a later update

**Comment by NiiRoZz** [comment]
I check for update the file to eden editor but i ahve error when i load mission in server when i have converted to Eden Format, if issue persist i will post a feedback to Bohemia

**Comment by MrHeavyMetal** [comment]
It sounds like an issue for Bohemia, I have updated the mission to the new format with no problem, Mind i did it with a fresh mission, if yours has custom scripting that could be why

**Comment by magicianaos** [comment]
@NiiRoZz  Thanks for answer :)

**Comment by NiiRoZz** [comment]
@MrHeavyMetal I use this build but it's not the converting it's when i launch my server i have an error

**Comment by OfficialNoms** [comment]
Hi guys,

In order to import Altis Life into the 3DEN editor, you search for and correct any markers that have the same variable name as other markers. In the latest version, car1_1 existed twice, and I believe there may have been a couple of others. I fixed these issues, as well as removed any spaces from variable names, and the mission imported correctly into the new 3D editor. 

I will be submitting my modified .sqm which is enabled for the 3D editor shortly.

**Comment by danielstuart14** [comment]
Already fixed, but thank you all...
https://github.com/ArmaLife/Altis/commit/5cf6f37d4ab060abe246f6e67521136b09d97aa7

**Comment by NiiRoZz** [comment]
@OfficialNoms if you can put here your modified .sqm please, thanks you so much.

**Comment by healthstr** [comment]
any help update on this :)

**Comment by HyunsukBaek** [comment]
@OfficialNoms im also wating ur file  :) thx

**Comment by Nesias** [comment]
i had the same problem, so far i can confirm that it is a result of an wrong named marker (car1_1 exist twice), after fixing that every thing worked fine

**Comment by DiabolicaTrix** [comment]
I made a pull request to correct this little bug.

**Comment by Jawshy** [comment]
For reference: pull request was #382 

/closed
