### ISSUE TITLE
Cant pickup money

### ISSUE THREAD

**Issue by Kimax89** [ArmaLife/Altis#304]
Its not possible to pickup money from the ground.

I tapped the windows-key many times when looking at the money and it dosnt pick them up.

**Comment by dardothemaster** [comment]
It's windows + T.

**Comment by OfficialNoms** [comment]
Usually using a shift + t and then windows key will work in 99.9% of cases.

**Comment by sargken** [comment]
This doesn't fix the issue, it's relevant and should pursue a different way in handling the pickup action. Maybe addaction or keep windows hey but do it by the distance instead of cursortarget

**Comment by HyunsukBaek** [comment]
I HAVE THIS ISSUE TOO, v4.4 still happens.

**Comment by HyunsukBaek** [comment]
i tried window + T and then it works well. sorry
