### ISSUE TITLE
Cops: Crushing a vehicle (removes from DB) [Suggestion]

### ISSUE THREAD

**Issue by DarkSilencerZA** [ArmaLife/Altis#314]
As the title says - an option added for cops to be able to both crush and impound. Impound obviously means sent to garage (which we have) and then the crush option would delete the vehicle from the db.

**Comment by MrHeavyMetal** [comment]
I love this suggestion

**Comment by DarkSilencerZA** [comment]
All working - will do pull request as soon as my github stops being full of shit and @danielstuart14 helps me fix it :D

**Comment by Heavybob** [comment]
Cops can blow up cars. Isn't that the same thing?

**Comment by Jawshy** [comment]
@Heavybob, same result; different execution.

**Comment by DarkSilencerZA** [comment]
@Heavybob How? Shooting it? Dropping it from a chopper?

**Comment by Heavybob** [comment]
However you want to destroy the car, it can be creative fun for police.
