### ISSUE TITLE
Vehicle claiming [Suggestion]

### ISSUE THREAD

**Issue by DarkSilencerZA** [ArmaLife/Altis#315]
Used at the chop shop - you have the option to either chop or claim. Claim obviously would then change ownership to the person who claimed it (but shows stolen and the original owners name when checking the registration).

**Comment by dardothemaster** [comment]
Something like this? http://pastebin.com/6btiwq1M

**Comment by DarkSilencerZA** [comment]
All working - will do pull request as soon as my github stops being full of shit and @danielstuart14 helps me fix it :D
