### ISSUE TITLE
Config option to enable illegal item saving in vehicles [suggestion]

### ISSUE THREAD

**Issue by MrHeavyMetal** [ArmaLife/Altis#320]
Basically add the ability to enable illegal items (coke, weapons etc) to be saved in vehicles inventory the same way normal items are

**Comment by NiiRoZz** [comment]
For  weapon already illégal save, but for y items go to véhicle store in life server and you have any array resourceitems, put items you don't want to save it inside

**Comment by Jawshy** [comment]
Altis/life_server/Functions/Systems/[fn_vehicleStore.sqf, line 14](https://github.com/ArmaLife/Altis/blob/master/life_server/Functions/Systems/fn_vehicleStore.sqf#L14): 
```
_resourceItems = ["oil_unprocessed","oil_processed","copper_unrefined","copper_refined","iron_unrefined","iron_refined","salt_unrefined","salt_refined","sand","glass","diamond_uncut","diamond_cut","rock","cement","heroin_unprocessed","heroin_processed","cannabis","marijuana","cocaine_unprocessed","cocaine_processed","turtle_raw"];
```
