### ISSUE TITLE
Macro Removal - Assistant Program Idea

### ISSUE THREAD

**Issue by ColinM9991** [ArmaLife/Altis#322]
So it's no surprise that the macros in Altis Life now are completely useless, pointless and unnecessary - which is kind of Tonic's trademark.

I'm thinking of creating another regex program to replace all macros with their original code, or do it manually because having SEL as a macro is a waste of time when the _this select function has never changed in the entirety of ArmA's lifetime.

How would everybody feel about this change for more readable and more meaningful code?

**Comment by sargken** [comment]
I think its a waste of time because it works fine right now why change it. It also condenses code so i like it

**Comment by ColinM9991** [comment]
It condenses code, but simply put it's horrible.

Altis Life is supposed to be a community based project which this repository portrays an image of, yet the macros being used are confusing to look at when they're macros that call other macros within another macro, this being said while my occupation is Software Developer - so imagine what somebody less experienced, and interested in contributing, sees.

A waste of time, or time lost, yes, but my time - more than happy to do this if it is something that will be merged in.

I'm interested in changing because it helps people learning the language contribute more without having some horrible "standard" made by Tonic forced in to their mind thus thinking that languages, programs or even future development work should be done this way, quite frankly this is something that would result in a comical scenario of you being fired if you were to do this in a real life development situation.

**Comment by dardothemaster** [comment]
Personally i think that macros could be useful,as often they are replacing long lines (Except for the gvar,svar,etc),take as example the one named 'LIFE_SETTINGS',which allows to take data from the main config file using only a short command

**Comment by baua1310** [comment]
i think @ColinM9991 's idea to remove the macros  is very godd and should have been done as fast as possible

**Comment by ColinM9991** [comment]
Replying from my mobile currently

The long lines will have macros like classic altis life, but is there
really any need for "EQUAL"? Macros are useful when code is subject to
change, isEqualTo has never changed in the entirety of ArmA.

My suggested changes will only remove macros like SEL, EQUAL, EXTDB etc -
the primarily pointless ones, any shorteners will be turned in to functions
as they rightfully should be.

**Comment by danielstuart14** [comment]
some of them are pretty useless, and I don't even use them...
But, some like FETCH_CONFIG, LICENSE_VARNAME, etc are very useful...

**Comment by ColinM9991** [comment]
I'll go through the macro file this weekend and remove the useless stuff
that only adds confusion, I'll update both mission and life_server and
propose the changes to see what people think.

Config fetching macros will be alright since they serve a purpose, but no
matter how I look at it - SEL will never serve a purpose and only waste
time debugging when importing previous version releases/content.

**Comment by trinitynet** [comment]
i agree with @ColinM9991 when I'm playing with the code ESPECIALLY in debug i don't have those macros and just makes it a pain... but some macros are useful

**Comment by fEcAlMaTteR** [comment]
They were confusing at first for me.  But I find them quite handy now.

**Comment by Heavybob** [comment]
Handful of times this has been brought up. Macros make the world easier and removing them to be replaced with raw statements is madness unless you have a better idea.
