### ISSUE TITLE
Config for Keys given to people being consistant [suggestion]

### ISSUE THREAD

**Issue by MrHeavyMetal** [ArmaLife/Altis#323]
Basically if i give a car key to a friend that key should then stay with him until he chooses to drop it, and should stay through server restarts etc

**Comment by silvercn** [comment]
Nice idea, like it :)

**Comment by Heavybob** [comment]
What happens if someone steals / lockpicks the car?

**Comment by MrHeavyMetal** [comment]
Perhaps put a check in to see if the key was given or stolen? perhaps just do if for houses?

**Comment by danielstuart14** [comment]
Maybe, we can attach the keys to the player inv. If player dies, he looses all his keys. And it would be dropped in the ground.

Also, add an option in garage, to change keys.

**Comment by Heavybob** [comment]
I can only see people getting angry after they die. Loosing a veh and not being able to nlr to get it back.

**Comment by danielstuart14** [comment]
that's only for non-owners

**Comment by MrHeavyMetal** [comment]
If the keys stayed after death if you are the original owner then i love the idea

**Comment by Heavybob** [comment]
Someone mentioned this to me on my server. When you knock someone out, it should surrender the keys. owned.

**Comment by Kimax89** [comment]
Can we please do the same for houses?

**Comment by silvercn** [comment]
What if you have more then one key, also what about keys that you got from a friend? All keys getting stolen?

**Comment by fEcAlMaTteR** [comment]
This would be nice for houses/garages.  Possibly a way to make a vehicle your own instead of chopping(Keep status of stolen.  Possibly removing it after a certain amount of time.)  As for dropping house/car keys when killed will likely open a shit storm.
I would suggest maybe redoing the rob player system with a way to take their inventory or keys.

**Comment by Heavybob** [comment]
Gang stolen cars?

**Comment by NiiRoZz** [comment]
If you want this features go code it, for me this feature can't in Tonic Mission, it's ez to code, just use bdd with player id of player give the keys and use script add the key when player connected
