### ISSUE TITLE
Weed can be processed without buying the License

### ISSUE THREAD

**Issue by silvercn** [ArmaLife/Altis#324]
Not sure if cocaine is also affected but i think yes.
Grab some weed and go to the processor and just process it without buying the license.
Found this as i added some items

Looks like something is wrong in processAction.sqf

if (_exit) exitWith {life_is_processing = false;hint localize "STR_NOTF_NotEnoughItemProcess";};

if(_vendor in [mari_processor,coke_processor,heroin_processor,lsd_processor,uran_processor]) then {
	_hasLicense = true;
} else {
	_hasLicense = LICENSE_VALUE(_type,"civ");
};

**Comment by DarkSilencerZA** [comment]
It can be, yes, but then you either make the time that it takes like 10x longer OR you make it a shit ton more expensive. Problem solved :+1:

**Comment by Jawshy** [comment]
All drugs - cocaine, weed, and heroin - can be processed without the respective processing licence. As @DarkSilencerZA mentioned, the processing time is significantly increased and there is also a tax for each unit that is processed.
