### ISSUE TITLE
Whats going on here guys

### ISSUE THREAD

**Issue by Liam0** [ArmaLife/Altis#325]
![untitled](https://cloud.githubusercontent.com/assets/7563573/13258511/b9a0f31a-da53-11e5-823d-9dc05c3315d3.jpg)

im not sure if its causing any issues but this seem a bit random, is it intended?

**Comment by dardothemaster** [comment]
They should not be causing any issue,just ignore them,as probably mysql does.

**Comment by NiiRoZz** [comment]
If causing no issue i think MresToArray and MresArray don't need anymore

**Comment by tkcjesse** [comment]
Its mresarray

**Comment by Liam0** [comment]
Yeah so far haven't noticed any problems

**Comment by danielstuart14** [comment]
that's an bug, and it'll fucks the saving gear system if enabled...

**Comment by Heavybob** [comment]
Confirmed, it has fucked the gear saving system.

**Comment by danielstuart14** [comment]
should be fixed now. Thx @Liam0
