### ISSUE TITLE
Cleanup BUG, RPT LOG

### ISSUE THREAD

**Issue by CamaroZ** [ArmaLife/Altis#328]
After 2 or more players disconnect, the cleanup script default of Altis Life, spam these error's in RPT.

All RPT Log:
http://pastebin.com/zWu0bG8X

Server: Object 3:3 not found (message Type_119)
Server: Object 3:3 not found (message Type_91)
Warning: Cleanup player - person 2:1214 not found
Warning: Cleanup player - person 2:4 not found
Client: Local object 2:1217 not found
Server: Object info 2:1217 not found during Changing Owner
Server: Object 3:6 not found (message Type_91)
Client: Local object 2:1221 not found
Server: Object info 2:1221 not found during Changing Owner
Server: Object 3:3 not found (message Type_91)
Server: Object 3:3 not found (message Type_119)
Server: Object 3:6 not found (message Type_119)

Sorry my english, I am from Brazil

**Comment by danielstuart14** [comment]
Seems like one of your players is returning null...
Hmmm...

(hu3hu3) ;)

**Comment by CamaroZ** [comment]
Como eu vejo isso veio?

**Comment by CamaroZ** [comment]
Então eu tentei, rodar denovo com a missão padrão depois de logar e deslogar umas 9 vezes começa o erro.

**Comment by tkcjesse** [comment]
From what ive read on the bi forums this is common rpt spam and is okay...

**Comment by HyunsukBaek** [comment]
fucking spam log i got too like this. 
how to avoid or ignore this spam???
