### ISSUE TITLE
Way to use stringtable for addactions

### ISSUE THREAD

**Issue by AveUrsus** [ArmaLife/Altis#33]
I found a way to store all add actions in stringtable.xml
1) Change 
this addAction["Market",life_fnc_virt_menu,"market"];
to this:
this addAction[(localize "STR_ACT_market"),life_fnc_virt_menu,"market"];
2) add pakage "actions" to string table. and keys for all actions.
<Package name="Actions_for_map">
<Original>Market</Original>
<Russian>Рынок</Russian>
</Package>

Working OK, but couse mission.sqm grow up.
Do we need it?

**Comment by danielstuart14** [comment]
it's good for multilanguage. 
But will need some hand work.

**Comment by AveUrsus** [comment]
OK, ill handle it in a few days

**Comment by Heavybob** [comment]
As long as Pirate is supported finally. We must not forget our Pirate Origins.

**Comment by AveUrsus** [comment]
Bob, what? ;)

**Comment by ClavosPL** [comment]
At my last pull request(shops on stations) some addaction strings are linked to stringtable
example line 2078 this addAction[localize ""STR_MAR_Car_shop"",life_fnc_vehicleShopMenu.....
and others, heli shops etc. , how you see it is another way to do this (two " " without ( ) )

Please daniel tell what wersion we putt in mission.sqm in addaction to unificate mission code and who must do this. I see no reason to 2 person work on this, When that will be created by AveUsers then i translate only the new lines in stringtable. Tell what we do.

**Comment by ClavosPL** [comment]
Al least generally a lot of STR_MAR strings in stringtable.xml, are ready to put in mission.sqm

**Comment by danielstuart14** [comment]
@ClavosPL we can use STR_MAR strings. If you want to do it...

**Comment by ClavosPL** [comment]
I do this, at sunday i will be ready to pull

**Comment by AveUrsus** [comment]
Ok. ill wait for your pull and add russian translation

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/04c8db5143d94e07b12e266ee5cefc3e2c4c1380
https://github.com/ArmaLife/Altis/commit/4c027a3d5f559dd1c2696a8f2f2572c4eaef858a
https://github.com/ArmaLife/Altis/commit/2aa819ac460977341734eb50343fdf5d437010c3

**Comment by tkcjesse** [comment]
Whats "MAR"? sorry if this should be obvious...

**Comment by Heavybob** [comment]
Where is Pirate Speak Support?

**Comment by danielstuart14** [comment]
Abbreviation for marker
