### ISSUE TITLE
Moving Drug Dealer

### ISSUE THREAD

**Issue by dardothemaster** [ArmaLife/Altis#342]
Hello,in my opinion the three drug dealers(Npcs) should be removed until only one remains.In fact it would be nice to set some waypoints and give him a vehicle so he can move through the markers. The cool thing is that player won't be able to know where actually the dealer is.

**Comment by healthstr** [comment]
That would be cool or you could ask an npc at a bar or something to get the location of the drug dealer, this would allow the drug dealer to move to different location.

**Comment by dardothemaster** [comment]
Yes nice idea! I was thinking even about random path,so it wont be predictable

**Comment by goatboynz** [comment]
ill post up my script for this when i get home works a treat. Ya set ya way points on map then the guy will walk or drive around. I have him set up for a black market atm but you can use him for anything.

**Comment by danielstuart14** [comment]
That's something server admins should add... Isn't a good thing for framework
