### ISSUE TITLE
Error in expression - fn_questionDealer

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#355]
The following appears in the client/local.rpt file when a police officer questions a drug dealer. 

```
15:11:59 Error in expression <;
};
[(_x select 0),(_x select 1),"483",_val] remoteExecCall ["life_fnc_wantedAd>
15:11:59   Error position: <_val] remoteExecCall ["life_fnc_wantedAd>
15:11:59   Error Undefined variable in expression: _val
15:11:59 File mpmissions\__CUR_MP.Altis\core\cop\fn_questionDealer.sqf, line 21
15:11:59 Error in expression <;
};
[(_x select 0),(_x select 1),"483",_val] remoteExecCall ["life_fnc_wantedAd>
15:11:59   Error position: <_val] remoteExecCall ["life_fnc_wantedAd>
15:11:59   Error Undefined variable in expression: _val
15:11:59 File mpmissions\__CUR_MP.Altis\core\cop\fn_questionDealer.sqf, line 21
```

The dialogue box will not display who has sold to the drug dealer recently, but any players whom have will show on the wanted list and in the database. 
![](http://puu.sh/noi7Y/4d8ac427a4.png)

Relevant file(s): Altis/Altis_Life.Altis/core/cop/[fn_questionDealer.sqf](https://github.com/ArmaLife/Altis/blob/34503036b9184ce56503506dfe7707fca940f5e7/Altis_Life.Altis/core/cop/fn_questionDealer.sqf)

Full .rpt files available on request. 

Game version: 1.56.134627
Mission version: v4.4r1 - latest commit: 8c0aa548b24862ce943420b4258d274311ba29f8

**Comment by danielstuart14** [comment]
should fix https://github.com/ArmaLife/Altis/commit/2c21fabfba19ed0bb5a794d589e41cd01c04ad7b

**Comment by Jawshy** [comment]
@danielstuart14, the commit did not fully fix the issue. There are no longer any .rpt error messages, however the dialogue box still does not display a list of players who have recently sold to the drug dealer. Furthermore, the any players who sold to the dealer are placed on the wanted list for drug trafficking but with a bounty of $0.

**Comment by Liam0** [comment]
im not sure if this is releated. a while back i had a problem adding people to the wanted list if you do it from the bounty list. im not sure if its still a problem i never really had time to look into it.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/35695ce288702c398f0b62ea2d1d54c522122871
should fix
