### ISSUE TITLE
Vehicle Shop Preview Menu - Potential Log Spam Abuse

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#357]
It is easily possible to spam the local/client.rpt, and createVehicle and remoteExec BattlEye logs by rapidly switching between vehicles in the vehicle shop 3D preview menu. 

Doing this with any vehicle will spam entries similar to `21:48:59 Ref to nonnetwork object 6a348100# 1780952: quadbike_01_f.p3d` in the local/client.rpt log. Doing this with vehicles that contain parachutes in their inventories (i.e. helicopters) will spam `B_Parachute` in the createVehicle.log. Doing this with vehicles that have multiple textures/skins will spam entries similar to `ton_fnc_setobjvar [<NULL-object>,"color",1,true]` in remoteExec.log. 

Would it be possible to implement anti-spam/cool-down code to help prevent or at least reduce the log spam? 

Game version: 1.56.134627
Mission version: v4.4r1 - latest commit: cd91e7c6e9509165213649931990ed06a840c28d

**Comment by Heavybob** [comment]
Verified.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/pull/418

**Comment by NiiRoZz** [comment]
#419

**Comment by NiiRoZz** [comment]
65b14b9996cf673152d7befa004911ddb37f6504

**Comment by Jawshy** [comment]
Now even more of the BattlEye logs can be spammed with entries like: 

###### remoteExec
```
24.03.2016 13:02:10: playerName (10.0.0.7:2316) 12345678901234567890123456789012 - #0 "life_fnc_hideobj [<NULL-object>]"
24.03.2016 13:04:00: playerName (10.0.0.7:2316) 12345678901234567890123456789012 - #0 "ton_fnc_setobjvar [4f356b00# 1814827: hatchback_01_f.p3d REMOTE,"color",1,true]"
```

###### createVehicle
```
24.03.2016 12:53:48: playerName (10.0.0.7:2316) 12345678901234567890123456789012 - #1 "B_Quadbike_01_F" 4:23 [5754,5390,-181]
24.03.2016 13:29:51: playerName (10.0.0.7:2316) 12345678901234567890123456789012 - #1 "C_Heli_Light_01_civil_F" 7:309 [5988,7045,-168]
```
If the vehicle's inventory contains `B_Parachute`: 
```
24.03.2016 13:30:29: playerName (10.0.0.7:2316) 12345678901234567890123456789012 - #0 "B_Parachute" 7:549 [0,0,0]
```

###### attachTo
```
24.03.2016 13:00:53: playerName (10.0.0.7:2316) 12345678901234567890123456789012 - #0 6:4 B_Quadbike_01_F 2:1202 Land_HelipadEmpty_F -1 [5495,6095,16033]
24.03.2016 13:30:30: playerName (10.0.0.7:2316) 12345678901234567890123456789012 - #0 7:608 NetworkMessageCreateHelicopterRTD 2:1202 Land_HelipadEmpty_F -1 [7116,5103,18734]
```

###### setVariable
```
24.03.2016 13:02:10: playerName (10.0.0.7:2316) 12345678901234567890123456789012 - #0 "life_veh_color" = 7 7:4 B_Quadbike_01_F
24.03.2016 13:30:00: playerName (10.0.0.7:2316) 12345678901234567890123456789012  - #0 "life_veh_color" = 1 7:371 NetworkMessageCreateHelicopterRTD
```

###### addBackpackCargo
If the vehicle's inventory contains `B_Parachute`: 
```
24.03.2016 13:29:49: playerName (10.0.0.7:2316) 12345678901234567890123456789012 - #0 7:285 B_Parachute 0:0
```
