### ISSUE TITLE
Adding Housing with Eden editor

### ISSUE THREAD

**Issue by torchgodz** [ArmaLife/Altis#361]
With the release of the new Ed3n editor server owners are now able to put in houses where ever they want.  Which is great and easy for them to put in new housing for there player. But i have tried this and you can add it and on the first restart you can buy they house and everything just like normal until the server restarts then the house is back up for sale you have to buy it all over again. Is there a way to make it so that the houses will stay just like the houses that are native to the map stay as someones bought house. I really think this could change the dynamic of altis.

**Comment by MrHeavyMetal** [comment]
The problem is also if you disconnect and reconnect to the server, i have the same issue except you cant rebuy the house but cant use it or access it either

**Comment by baua1310** [comment]
I made a [tutorial](https://www.global-gamer.com/home/wbb/index.php/Thread/4572-Tuturial-Selbst-gesetzte-H%C3%A4user-zu-Housing-hinzuf%C3%BCgen/) on a german Gaming Board about how to add mapped houses to the housing system correctly. The only thing is that these aren't placed in the mission but in the init.sqf of the server.

**Comment by danielstuart14** [comment]
eden isn't support, until the next arma update

**Comment by dardothemaster** [comment]
As you can see on the [wiki](https://community.bistudio.com/wiki/nearestBuilding) , nearestBuilding does not detect objects placed in editor. The tutorial made from baua should work even if the objects are loaded from the mission.sqm.

**Comment by baua1310** [comment]
the problem with thw mission.sqm is that houses are not always on the exact same position

**Comment by dardothemaster** [comment]
Uhm,with the new eden formatting it should be okay

**Comment by baua1310** [comment]
ok that fact I havn't known
