### ISSUE TITLE
some files not  found error logs.

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Altis#367]
Unexpected message data (message struct NetworkMessageRunInitSitesScript, item site)
Before (0x00000000): 00 00 00 00 03 03 fc 02 43 01 d6 23
Current (0x0000000c):
Starting mission:
 Mission file: Altis_Life
 Mission world: Altis
 Mission directory: mpmissions\Altis_Life.Altis\
Attempt to override final function - bis_functions_list
Attempt to override final function - bis_functions_listpreinit
Attempt to override final function - bis_functions_listpostinit
Attempt to override final function - bis_functions_listrecompile
Attempt to override final function - bis_fnc_missiontaskslocal
Attempt to override final function - bis_fnc_missionconversationslocal
Attempt to override final function - bis_fnc_missionflow
MovesType CfgGesturesMale load time 32 ms
Animation a3\cargoposes_f_heli\anim\passenger_inside_5aim_obstructed.rtm not found or empty
Animation a3\cargoposes_f_heli\anim\passenger_inside_5aim_fromobstructed.rtm not found or empty
Animation a3\cargoposes_f_heli\anim\passenger_inside_5aim_toobstructed.rtm not found or empty
Animation a3\cargoposes_f_heli\anim\passenger_inside_5aimpistol_obstructed.rtm not found or empty
Animation a3\cargoposes_f_heli\anim\passenger_inside_5aimpistol_fromobstructed.rtm not found or empty
Animation a3\cargoposes_f_heli\anim\passenger_inside_5aimpistol_toobstructed.rtm not found or empty
MovesType CfgMovesMaleSdr load time 3838 ms
No speaker given for Luke Thompson
No speaker given for Teshi Tinibu
No speaker given for Imre Hoxha
No speaker given for Gula Inouyie
No speaker given for Kyle Harrison
No speaker given for Batou Okonjo
No speaker given for Kuang Wong
soldier[B_diver_F]:Some of magazines weren't stored in soldier Vest or Uniform?
No speaker given for Jake Halliwell
No speaker given for Lucas Clarke
No speaker given for Ian Lee
No speaker given for Max Robertson
No speaker given for Ali Ngige
No speaker given for Nathan Wright
No speaker given for Adam Anderson
No speaker given for George Bennett
No speaker given for Guo Chong
No speaker given for Shen Zao
No speaker given for Ben Ryan
No speaker given for Ryan White
No speaker given for Andy Johnson
No speaker given for Ma Tsai
No speaker given for Thomas Williams
No speaker given for David Smith
No speaker given for Sean Abbey
soldier[B_diver_F]:Some of magazines weren't stored in soldier Vest or Uniform?
No speaker given for William Stewart
No speaker given for Dumi Egwu
No speaker given for Michael Young
No speaker given for Colin Johnson
No speaker given for Keith MacDonald
No speaker given for Ewan Davis
No speaker given for Andy Phillips
No speaker given for Benjamin Smith
No speaker given for Callum Snowe
Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 1c not found
Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 2c not found
Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 3c not found
Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 4c not found
Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 5c not found
Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 6c not found
Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 7c not found
Wrong vertex mapping for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Selection 8c not found
Wrong geometry convex component mapping  for person collision geometry found in a3\characters_f_epc\civil\c_nikos_aged.p3d. Convex component number 3. not found
No speaker given for Dimitiros Savalas
No speaker given for Dimitiros Petridis
No speaker given for Gekas Dimitriadis
No speaker given for Janos Mylonaki
No speaker given for Vangelis Haikias
No speaker given for Giorgos Savalas
No speaker given for Rosi Melidoni
No speaker given for Kostas Kanelloupou
No speaker given for Arion Manetta
No speaker given for Sotiris Baros
No speaker given for Achilleas Xenakis
No speaker given for Lafteris Petridis
No speaker given for Angelos Lagos
No speaker given for Kostas Vidales
No speaker given for Janos Stanis
No speaker given for Kyriakos Isofidou
No speaker given for Vasilis Oikonomopulu
No speaker given for Evripidis Strambopoulos
No speaker given for Nikas Athanasiadis
No speaker given for Giourkas Doukas
No speaker given for Sotiris Zenon
No speaker given for Mimis Xenakis
No speaker given for Anthis Mylonaki
Strange convex component322 in a3\structures_f\research\dome_big_f.p3d:geometryFire
Strange convex component327 in a3\structures_f\research\dome_big_f.p3d:geometryFire
Error: Object(2 : 8) not found
Error: Object(2 : 10) not found
Error: Object(2 : 12) not found
Error: Object(2 : 17) not found
Error: Object(2 : 19) not found
Error: Object(2 : 21) not found
Error: Object(2 : 23) not found
Error: Object(2 : 25) not found
Error: Object(2 : 27) not found
Error: Object(2 : 29) not found
Error: Object(2 : 31) not found
Error: Object(2 : 33) not found
Error: Object(2 : 35) not found
Error: Object(2 : 37) not found
Error: Object(2 : 39) not found
Error: Object(2 : 41) not found
Error: Object(2 : 43) not found
Error: Object(2 : 140) not found
c:\w\stable\futura\lib\network\networkserver.cpp NetworkServer::OnClientStateChanged:NOT IMPLEMENTED - briefing!
"extDB2: Connected to Database"
 Mission id: 260071b51d938063ccc947c970643e621978b037
Warning: Cleanup player - person 2:3 not found
Error: Object(3 : 10) not found

is that a issue?

**Comment by NiiRoZz** [comment]
No !
