### ISSUE TITLE
virtual item can't save DB  -

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Altis#371]
when i put the y items to trunk and then store vehicles,  y items successfully saved at database before ff82f18636fa8919c031fb1eb6a70ca4c7917d68  applied my repository

but i applied patches after ff82f18636fa8919c031fb1eb6a70ca4c7917d68, 
it's not working. 
plz confirm that merged after ff82f18636fa8919c031fb1eb6a70ca4c7917d68

**Comment by danielstuart14** [comment]
it isn't related to this commit... Should be other. 
Are you getting any RPT Error?

**Comment by HyunsukBaek** [comment]
hmm. this is not logs about this issue, i guess,

but  abnormal logs are : 


soldier[B_diver_F]:Some of magazines weren't stored in soldier Vest or Uniform?

c:\w\stable\futura\lib\network\networkserver.cpp NetworkServer::OnClientStateChanged:NOT IMPLEMENTED - briefing!

c:\w\stable\futura\lib\network\networkserver.cpp ClearNetServer:NOT IMPLEMENTED - briefing!

and lots of Error: Object(2 : xx) not found

**Comment by danielstuart14** [comment]
Do you know if inventory is being saved? (vehicle Inventory)

**Comment by HyunsukBaek** [comment]
i didnt check inventory saving yet. i will try it now.

**Comment by HyunsukBaek** [comment]
i item is working well. gun and nv goggles in vehicle.

when i put the y item to trunk, y item save at database, but, 
run store vehicle in garage,  then  erased it

**Comment by Liam0** [comment]
Yeah im just quadruple checking again =)

**Comment by Liam0** [comment]
@HyunsukBaek would you please check out https://github.com/ArmaLife/Altis/pull/376 and confirm if its working thank you =)

**Comment by HyunsukBaek** [comment]
Error in expression <VariableClient "life_garage_store";
};

+
if(getNumber(missionConfigFile >> "Lif>
  Error position: <+
if(getNumber(missionConfigFile >> "Lif>
  Error +: Type if, expected Number,Array,Not a Number
File life_server\Functions\Systems\fn_vehicleStore.sqf, line 76


@Liam0   IT'S NOT WORKING AND ERROR OCCURS 

i patched f323251 and ea5ae17.    and then , not only y-item can't saving but also storing vehicles fails.

**Comment by Liam0** [comment]
make sure you didn't paste a "+" from github by mistake in vehiclestore.sqf

**Comment by HyunsukBaek** [comment]
oh..

**Comment by Liam0** [comment]
Thanks @HyunsukBaek
