### ISSUE TITLE
flawed call of fnc_asyncCall in fn_spawnVehicle (server)

### ISSUE THREAD

**Issue by Nesias** [ArmaLife/Altis#372]
In [fn_spawnVehicle.sqf](https://github.com/ArmaLife/Altis/blob/master/life_server/Functions/Systems/fn_spawnVehicle.sqf) at line 75 the following code can be found:
`[_query,false] spawn DB_fnc_asyncCall;`

This will create an error message in rpt (but will work, because param safeguard).

Code should be:
`[_query,1] spawn DB_fnc_asyncCall;`

**Comment by danielstuart14** [comment]
thx https://github.com/ArmaLife/Altis/commit/6bae45b4d2aa2d61f07677bc815b2d16d637d8cf
