### ISSUE TITLE
Police Grid Reference Emergency TXT - Suggestion

### ISSUE THREAD

**Issue by Heavybob** [ArmaLife/Altis#38]
I have seen this on only one server but feel it should be put into the main build.

When someone txt messages cop, it should display the grid reference of where the origin of the txt came from. Including this minor feature will help those small police forces getting harassed by prank callers.

**Comment by tkcjesse** [comment]
@danielstuart14 Are you okay with this? I'll do a pull if you want it added.

**Comment by danielstuart14** [comment]
yes, but add this as an option on config_master.

**Comment by danielstuart14** [comment]
set true as default.

**Comment by tkcjesse** [comment]
@danielstuart14 since all messaging is handled in life_server\functions.sqf and done with compileFinal is it possible to?

**Comment by Heavybob** [comment]
I also would like to see this done also with reporting to cops. 

If the player is in a gang then it txt messages the whole gang the police messages and if a cop txt messages a single player who is in a gang, it messages the whole gang. 

Adding this in would stop any confusion of declaring a raid of Kavala or some other bogus situations which happen when people claim they msged cops or not.

**Comment by tkcjesse** [comment]
@Heavybob yes, what I have will add it for player to admin/ems/cop messages. I just need help with the life_settings

**Comment by Heavybob** [comment]
This will also stop corrupt cops and metagaming.

**Comment by danielstuart14** [comment]
In Life_Settings class on config_master add:
```example = true;```

This is equal to: ```example = 1;```

So, to add a check just: ```if(EQUAL(LIFE_SETTINGS(getNumber,"example"),1)) then {```

**Comment by tkcjesse** [comment]
@danielstuart14  Yes, correct. But all of the messaging stuff is handled server side in https://github.com/ArmaLife/Altis/blob/master/life_server/functions.sqf

So for some reason it's not cooperating properly.

**Comment by danielstuart14** [comment]
okay, pull-request it as it is and I'll add the checks somehow.

**Comment by tkcjesse** [comment]
Sounds good.

**Comment by Heavybob** [comment]
Closing as its merged into main build.
