### ISSUE TITLE
phone bug : inventory display can not refresh immediately

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Altis#380]
when i drop an y-item in phone -> player menu inventory, it's not refresh immediately.
when i go into same menu again, and then i can  check removed an y item. 

display cannot refresh at one time.

**Comment by TravisPrice** [comment]
Yah, The phone was never finish needed to be reworked but @danielstuart14 is working on one as I am working on other projects contains some neat stuff which is coming soon. But I will fix it and add a new pull request so those who have it now can update it
