### ISSUE TITLE
zero division error 

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Altis#384]
Error position: <select 3;
if(_half) then
{
[((_amount) />
  Error Zero divisor
File life_server\Functions\WantedSystem\fn_wantedBounty.sqf, line 23
Error in expression <ult != 0) then
{
_amount = _queryResult select 3;

it should be check before division of zero

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/d62410ebeec4ef748346d30a93e238d6b6399c11
