### ISSUE TITLE
New Player Menu!

### ISSUE THREAD

**Issue by KingRizla** [ArmaLife/Altis#387]
Please Guys for the love of all good things, please remove the new menu and use the old one again, not only are the new menu really ugly (no offence travis) but it is also buggy, numbers are not updating correctly and the interface is not that smart again, all players can see the admin tab and more, the only thing i can say about the new menu that i (and the rest of our server) thinks are sweet is the newly added dance moves. but please change it back to the old menu that we love and know. but thanks for the awesome "gamemode" (altis life) from Wattup Gaming

**Comment by Jawshy** [comment]
As this is a development repository for Alits Life RPG new features and changes are constantly being introduced and they may break other features, be broken, or unfinished. 

The new phone system needs refinement, yes, but allow sometime for it to be updated and let us know if it should be kept, reverted, or make optional.

**Comment by KingRizla** [comment]
i would say, let it be optional, so one can choose either to have the old layout or the new, 


this would make it easy for the server owners also, because allready we have had over 20 complaints about the new layout, everything from, it not updating correctly, to its a ingame advertizement for apple, and so far only 2 people from our server have been happy about the change. 

i do understand that in development new stuff will be added and maybe also removed if not living up to its full potential, but this is just my personal thoughts, why spend time working on a new player menu, when there is alot more that could be worked on that would benefit the players even more.

like being able to rob gas stations for example, this is only possible if you run a script, and balancing the prices ingame, for example it does not really make any sense that you can make more money on a single copper run, than you can on a single heroin/cocain/weed run, but maybe its just me that thinks like this. 

but seing that the old menu was working without problems, i  would have thought those would be some of the things to be focused on. 


but i would like to let it be known that this is not supposed to be disrespectful (even if some might find it to be) this is just my opinion and my thoughts. 



but to keep it on the subject, known bugs on the phone as of this moment is: 

1:non admins can see the admin tab on the phone. 
2: numbers (both in banking and item numbers in inv) is not updating before you have taken away the phone and taken it up again. 
3: non cop's can see the wanted list on the phone. 4
:when in a vehicle, you you by mistake take up the phone, you will get som sort of "mini gps" that will make it impossible to control your vehicle.

but again thank you all for the gamemode

**Comment by sargken** [comment]
It should be optional because this is framework and your adding in your own opinion to it.

**Comment by danielstuart14** [comment]
yeah, it'll be optional.
We're adding a new phone and it'll be the default option, but, the old interface will still exists

Here: https://github.com/ArmaLife/Altis/commit/fa62b076d720fcabdd483e18620961f9bb2bc2e6
(Look the comments)

**Comment by danielstuart14** [comment]
phone menu reverted
I'm going to add a new one
you can found images and some comments here:
fa62b07
b3ce3c1

**Comment by sargken** [comment]
@danielstuart14 Sounds Great Man
