### ISSUE TITLE
life_action_inUse Impound Delay [With HC]

### ISSUE THREAD

**Issue by trinitynet** [ArmaLife/Altis#388]
hey guys,

life_action_inUse is not being set false till some time after impounding a vehicle 30 - 60 sec's which is stopping players from being able to do anything for some time after.

No errors in the Clinet,Server,HC RPT Files

**Comment by Liam0** [comment]
i don't understand what should be causing this. is it just after you impound a vehicle u can't do any actions for a while?

**Comment by trinitynet** [comment]
@Liam0 basicly yes... im not sure what's causing this either.. all i know is life_action_inUse is not being set false till 30-60 secs after the veh has been impounded.. will put a vid up in a min

**Comment by trinitynet** [comment]
here @Liam0 excuse the shit mic and not using hint silent -.- https://www.youtube.com/watch?v=pH562z0DDdI&feature=youtu.be

**Comment by Liam0** [comment]
@trinitynet thx for the video. i dont have HC myself and the problem wasn't showing for me without

**Comment by fEcAlMaTteR** [comment]
I fixed this issue in PR#397

**Comment by fEcAlMaTteR** [comment]
this likely has to do with the hc using (owner _unit) PVC 
I've fixed this in PR#397 for vehicleStore  checking on it now

**Comment by trinitynet** [comment]
testing in a min

**Comment by fEcAlMaTteR** [comment]
Fixed in PR#397.  Was with hc using owner _unit.

**Comment by trinitynet** [comment]
Can confirm working, thanks again!
