### ISSUE TITLE
Abort timeout not working after re-logging

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#392]
The 10 second timeout before a player can abort does not appear again after re-logging. No .rpt log errors. Issue likely introduced in #390. 

Game version: [1.56.134787](https://dev.arma3.com/post/spotrep-00053)
Mission version: v4.4r1 - latest commit: ac954b0f2f0ea9b5ea1a8784618de008b01afdc2

**Comment by trinitynet** [comment]
@Jawshy  i believe this is because Life_fnc_escinterupt is looking for the spawn dialogue to be opened and then closed.

**Comment by trinitynet** [comment]
everything working on my end

**Comment by Jawshy** [comment]
Likewise. Fix with #401 and #404.
