### ISSUE TITLE
Error in expression - fn_copSearch

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#394]
The following appears in the client/local.rpt file when a police officer searches a restrained player. Searching otherwise performs without issue. 

```
18:42:21 Error in expression <(missionConfigFile >> "VirtualItems" >> _var >> "processedItem")) then {
_proces>
18:42:21   Error position: <_var >> "processedItem")) then {
_proces>
18:42:21   Error Undefined variable in expression: _var
18:42:21 File mpmissions\__CUR_MP.Altis\core\cop\fn_copSearch.sqf, line 26
```

Relevant file(s): Altis/Altis_Life.Altis/core/cop/[fn_copSearch.sqf](https://github.com/ArmaLife/Altis/blob/cab5b9a415250e4fb971e44f0daa665dae947078/Altis_Life.Altis/core/cop/fn_copSearch.sqf)

Full .rpt files available on request. 

Game version: [1.56.134787](https://dev.arma3.com/post/spotrep-00053)
Mission version: v4.4r1 - latest commit: ac954b0f2f0ea9b5ea1a8784618de008b01afdc2

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/8da7be9b84a801cef7832c711346663b3462e7cc should fix
