### ISSUE TITLE
WHAT IS NEXT?

### ISSUE THREAD

**Issue by Heavybob** [ArmaLife/Altis#4]
*REPOST FROM PREVIOUS GIT*
https://github.com/danielstuart14/Altis-Life/issues/41

@danielstuart14
https://trello.com/b/9urCslRT/altis-life
So, don't ask for features that are already added to this list.

**Comment by tkcjesse** [comment]
@danielstuart14 Could probably close this?

**Comment by danielstuart14** [comment]
not yet...

**Comment by flanks** [comment]
How about a new system for gathering stuff i must say i like the system a3l had with planting weed plants etc with the new command createObjects plants and other various stuff can be used https://forums.bistudio.com/topic/187670-new-command-createobject-for-decorative-objects/  but its no the dev build atm.. thanks

**Comment by Kimax89** [comment]
Are we actually using this issue to post what is next?
