### ISSUE TITLE
Police Texture

### ISSUE THREAD

**Issue by Kimax89** [ArmaLife/Altis#412]
How about adding some of the textures from http://altispolice.org

I specially like the way "Lincolnshire Police" textures look.

Perhaps it should be default in the AltisLife?

**Comment by trinitynet** [comment]
you guys not think you are taking this too far?
after-all this is meant to be a framework

**Comment by Liam0** [comment]
I have to agree with @trinitynet. Personalization like this should come down to the individual server / community.

**Comment by trinitynet** [comment]
@Liam0 check u'r gitter chat please

**Comment by Kimax89** [comment]
I just thought that since we allready have skins for cop and medic, then why not just go all in?

I dont  see AltisLife as JUST a framework, i see it as a full serverside mod pack filled with everything needed for an awesome RPG experience.

**Comment by sargken** [comment]
I can see both sides here.

**Comment by tkcjesse** [comment]
@Kimax89 The reason it's a framework is because your idea of an awesome RPG experience is different than mine and everyone elses...

**Comment by JohnMeiers** [comment]
I agree Tonic made this as a framework, for people to create their own server. For one 1 cop texture is fine, but to fully go all out and add textures to the framework is out of hand. This is meant for people to make their own server, and decide what what THEY want in a server not the development branch. I think you guys are going way to far on this!!! adding all kinds of custom stuff, you are taking away the excitement for other to build a server the way they want to. I think want really needs to be worked on is the framework making sure that bugs are keep to a minimum. I remember Daniel saying he wanted to keep the framework as close as possible to Tonic's. Remember the fun part about Altis Life is making it yourself !!!!!!!!

**Comment by KiritoKirigaya2601** [comment]
The mission is completely a framework, they give you a loadscreen, cop_uniform and medic_uniform default to start you off to edit the textures and create your own, but in total you can't ask them to include more textures as everything on here is being made custom by them all again, adding some textures would remove the individuality, it takes less than 2 minutes to add some textures, if you think some of the Lincolnshire police textures are good, then add them to your server, but don't ask them to add things which aren't needed.

@JohnMeiers - Your correct, They did say that they want the project to be as close to Tonic's version as possible, Altis Life is a framework, you  make it yours by editing it and making it amazing :)
