### ISSUE TITLE
Error in expression - fn_bountyReceive

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#416]
The following appears in the client/local.rpt file when a police officer sends a player on the wanted list to jail. The cop receives a $0 bounty regardless of what the player's bounty is on the wanted list. 

```
19:11:03 Error in expression <LAIN"];
};

life_atmbank = life_atmbank + _val;>
19:11:03   Error position: <+ _val;>
19:11:03   Error Generic error in expression
19:11:03 File mpmissions\__CUR_MP.Altis\core\cop\fn_bountyReceive.sqf, line 19
```

- Relevant file(s): 
  - Altis/Altis_Life.Altis/core/cop/[fn_bountyReceive.sqf](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/cop/fn_bountyReceive.sqf)

Full .rpt files available on request. 

Game version: [1.56.134787](https://dev.arma3.com/post/spotrep-00053)
Mission version: v4.4r1 - as of: ac954b0f2f0ea9b5ea1a8784618de008b01afdc2

**Comment by Heavybob** [comment]
Confirmed. Nice find @Jawshy

**Comment by danielstuart14** [comment]
hmmm, is it at least texting in the screen the right value?

I think it isn't receiving the bounty value.

**Comment by Jawshy** [comment]
no, the on-screen text says "You have collected a bounty of $0 for arresting a criminal."

**Comment by NiiRoZz** [comment]
Test with this commits : 504a7cb4d3273f97754cade062f290fabe0904eb

**Comment by danielstuart14** [comment]
Closing as it should be fixed. 

If needed, just ask for reopening.
