### ISSUE TITLE
Keys not returning to players on re-connect [HC]

### ISSUE THREAD

**Issue by trinitynet** [ArmaLife/Altis#417]
When a players vehicle is left out on the server and a player is disconnected or re-connects the keys for that vehicle will not be returned to the player unless the vehicle is stored and retrieved from the garage

**Comment by trinitynet** [comment]
i have not captured any script errors

**Comment by danielstuart14** [comment]
yes, I saw that sometime ago.
Isn't hard to fix, just query the vehicles that are active and push them to the key list.

I'll take a look on it.

**Comment by NiiRoZz** [comment]
I will fix it sorry for the wait.

**Comment by NiiRoZz** [comment]
fdaca80c79f2dc30143c847999031a61bbc1ccaa
