### ISSUE TITLE
Gang house restriction

### ISSUE THREAD

**Issue by Kimax89** [ArmaLife/Altis#420]
This is just an idea. what if gangs wasnt allowed to buy houses close to each other.

So that 2 players cant be neighbors if they are in different gangs.
Just to split up rival gangs. i think there will be too much fighting if rival gangs was neighbors.

**Comment by sargken** [comment]
No don't agree with. Limited the players for no reason. I want to see more gang fighting.

**Comment by Kimax89** [comment]
But i think that gangs should be able to claim areas, without being neighbors.

But if gangs are neighbors, then they will break NLR for sure.

**Comment by sargken** [comment]
They will break it regardless i dont think it should be in the framework
