### ISSUE TITLE
NIGHTSTALKER can't save in storageBox.

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Altis#421]
NIGHTSTALKER can't save in storage at house. another acc/item saved well. 
is this problem just happens to me?

**Comment by Kimax89** [comment]
i believe there is a restriction in what you are able to save in a storagebox. The nightstalker is normally not buy-able in the standart AltisLife. So you eather own or play on a custom server, that have added the nighstalker.

**Comment by Liam0** [comment]
works fine. 
![nightstalker](https://cloud.githubusercontent.com/assets/7563573/13898517/10d5cffa-edd4-11e5-9ebc-b3fc559cfbea.jpg)
