### ISSUE TITLE
Clothingbox not working

### ISSUE THREAD

**Issue by silvercn** [ArmaLife/Altis#422]
Just tested today the clothingbox and set it to true in masterconfig. But it doesn´t work for me. If someone else could test. Thanks

**Comment by Kimax89** [comment]
doesn't work for me ether.

**Comment by Heavybob** [comment]
Will test later when I run my patching.

**Comment by Heavybob** [comment]
What happens with it false?

**Comment by Heavybob** [comment]
Drop an RPT please both for server and client./

**Comment by dardothemaster** [comment]
Working perfectly,just make sure to disable    "clothing_noTP ",as the following code block is executed after the check of the clothing_box parameter


 `waitUntil {isNull (findDisplay 3100)};
if(EQUAL(LIFE_SETTINGS(getNumber,"clothing_noTP"),0)) then {
	{if(_x != player) then {_x hideObject false;};} foreach playableUnits;
	if(EQUAL(LIFE_SETTINGS(getNumber,"clothing_box"),0)) then {
		{if(_x != player && _x != _light) then {_x hideObject false;};} foreach _nearVeh;
	};
	detach player;
	player setBehaviour _oldBev;
	player setPosASL _oldPos;
	player setDir _oldDir;
	if(EQUAL(LIFE_SETTINGS(getNumber,"clothing_box"),1)) then {
		{deleteVehicle _x;} foreach [_testLogic,_ut1,_ut2,_ut3,_ut4,_ut5,_light];
	} else {
		{deleteVehicle _x;} foreach [_testLogic,_light];
	};
};`

this will simply restore every hidden object to its visible state , denying the player to see the "clothing box"

**Comment by Heavybob** [comment]
crazy shit be happening.
