### ISSUE TITLE
Federal Reserve - Cannot Replace Charge After Defuse

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#436]
If a civilian plants a blasting charge on the bank vault and then it is defused, another blasting charge cannot be placed. The hint will say "you must open the container." 

Police cannot repair the vault or the issue still persists if they do. No errors in RPT logs. Please try to reproduce. 

Game version: [1.56.134787](https://dev.arma3.com/post/spotrep-00053)
Mission version: v4.4r1

**Comment by DarkSilencerZA** [comment]
It's localized to the person who placed / defused it. We had to re-write the code for the fed as @danielstuart14 used a localized method to stop people from glitching into the fed. Not sure if it was ever fixed.

**Comment by danielstuart14** [comment]
it's about time to fix it. I'll take a look

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/d0bd2f3f3d141d09f6c44419034f2cb6ddd56ec6
https://github.com/ArmaLife/Altis/commit/94a0c6e1c2a8b3b1b1dd6a82ef4b6357c24d7035

I didn't test the repairDoor commit, but everything should work.
