### ISSUE TITLE
could u mining something? 

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Altis#437]
after patched about mining percent, we can't mining every -mine resources.

**Comment by Filippoml** [comment]
yes, it does not work :/

**Comment by dardothemaster** [comment]
As you can see it's my fault... I don't get why the format changed (probably breaking the script,it  worked before the pull,i swear :/)
Sorry again for that useless pull request.

**Comment by dardothemaster** [comment]
Fixed in #438 ,sorry again for this shit
