### ISSUE TITLE
question) duplication weapons.?

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Altis#439]
when I pick up a dropped weapon on ground from  near dead person, 
i got  a weapon already but also he has same(duplicated) weapon after he revived. 

is this problem about arma3 or Altis mod?
 
if arma3 side problem, how can we resolve this problem ourselves?

**Comment by danielstuart14** [comment]
the weapon should be deleted from the ground when the player dies.

Idk why it isn't.

**Comment by fresqo** [comment]
@HyunsukBaek was the player in a vehicle when he died?

**Comment by HyunsukBaek** [comment]
@fresqo  when player killed from other player, died himself (no food & water&accident)  and so on...

**Comment by Liam0** [comment]
@danielstuart14 i think it only calls the cleanup if the player gets revived but if the gun has already been picked up it would dupe i guess.

**Comment by danielstuart14** [comment]
it should be called when the player dies.... At least this is how it is set.

**Comment by danielstuart14** [comment]
The best thing to solve this, is set the player's items to be dropped when he dies and remove they from his inventory.

**Comment by tkcjesse** [comment]
@HyunsukBaek Can you try with this added? If I recall a few months ago the only issue I was really having with this was that if the player had a secondary weapon that you could then pickup the secondary but the primary wasn't an issue.

**Comment by tkcjesse** [comment]
Should be fixed in https://github.com/ArmaLife/Altis/pull/457.
