### ISSUE TITLE
SUPER JUMP

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Altis#442]
WHEN player use jump key on (something like stairs or raised spot ), the player acts super jump and die himself sometimes. it seems like GTA5 Super jump menu. i think it is a jump action(motion) bug.

**Comment by DarkSilencerZA** [comment]
Yep, something Arma related. I don't think it can be fixed. Only way would be to remove the jump ability via keyhandler.

**Comment by Liam0** [comment]
Give this a try and tell me if u run into any problems. i don't want to make a pull request for this little thing.

https://github.com/Liam0/Altis/commit/a7aba85e4f0892c8586efbb989752efadd5c9c63

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/7e67674df79cc4e8cd2d8e900627fb4804d2f26b
