### ISSUE TITLE
Fuel station pump service is free

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#443]
Re-fuelling your vehicle at a fuel station using @NiiRoZz' [pump service](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/Config_Master.hpp#L78-L79) will not cost anything. 

Relevant file(s): Altis/Altis_Life.Altis/core/shops/[fn_FuelStatOpen.sqf](https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/shops/fn_FuelStatOpen.sqf)

Game version: [1.56.134787](https://dev.arma3.com/post/spotrep-00053)
Mission version: v4.4r2 as of: 572f07ece95209795a01ef933aa2da7d0a9e9bf6

**Comment by Liam0** [comment]
it should be taking money off the bank, works for me but only did some quick testing.

**Comment by Liam0** [comment]
If its still a problem just reopen this, but it did take money of my bank during testing with the latest commits.
