### ISSUE TITLE
Auto-clikers

### ISSUE THREAD

**Issue by N1colas62** [ArmaLife/Altis#454]
Hi,

On my server, stupid player play with auto-clicker.
I have already Infistar but doesn't work..

On garage, they active there auto-clickers and they go in garage, and sell cars with this.

**Comment by NiiRoZz** [comment]
Already exist anti spam in Altis ...

**Comment by dardothemaster** [comment]
I think life_action_delay solved the issue

**Comment by danielstuart14** [comment]
garage auto-clicker doesn't work anymore.
