### ISSUE TITLE
SQM FILE CONVERTED TO EDEN EDITOR GIVES LOG SPAM

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Altis#455]
hi. contributors. 

i have 2 issues of spam server rpt logs. 

when i converted mission.sqm files to 3d editor, then logged SPAM as follows, 

when i selected "not first slot" in cop or medic role(group) 
-------------------------------------------------------------------
 - no leader
Group B Alpha 1-2 (0x2382a480) - network ID 2:1361
 - no leader
Group B Alpha 1-2 (0x2382a480) - network ID 2:1361
 - no leader
Group B Alpha 1-2 (0x2382a480) - network ID 2:1361
..... iteration. 
------------------------------------------------------------------

1 of issue : log spam like above paste text. 

2 of issue : when i choose role of player : cop, medic, civil... ) , the name of Group is change ECHO 1-X automatically NOT Alpha 1-X, i just change(converted) sqm file to eden editor, but also above logs are presented name 'Alpha xx'..  

and Could plz someone upload / commit sqm file is converted to 3d(eden) edior??? 

i lost 2 days!!! :(

**Comment by clackd1amond** [comment]
Just change player slot (red circle) to playable slot (purple circle). Can't remember how exactly those called

**Comment by danielstuart14** [comment]
I'm going to upload a mission converted. Headless client with eden was fixed in the latest arma patch, so, we can set mission as EDEN by default now.

**Comment by HyunsukBaek** [comment]
@clackd1amond   cop and medic slots has no red circle, just civ has red circle. change this?

**Comment by HyunsukBaek** [comment]
@clackd1amond  i did it u told, but still happened.

**Comment by HyunsukBaek** [comment]
@danielstuart14  when ?

**Comment by tkcjesse** [comment]
Chill Fam. I'll take a look at in a second.

**Comment by Kimax89** [comment]
@HyunsukBaek Take it easy. At the current state, AltisLife doesnt support the new mission format, but it will come. If you cant get it to work, then use the original mission file provided in the Master Build.

**Comment by DarkSilencerZA** [comment]
@danielstuart14 How much work is involved in converting it properly? All we did was place a player on the map > import into 3D and then delete the player (I'm assuming this was a dirty way of doing it and is therefore is incorrect?)

**Comment by danielstuart14** [comment]
@DarkSilencerZA that's the right way to do that, I just don't have time for opening the map, etc.

Also, you should export it with "Binarize" option unchecked and after that edit the author in the file to "Tonic" (:v)

If you want to....

**Comment by tkcjesse** [comment]
@danielstuart14 & @DarkSilencerZA I'll convert it quick in the next 2 hours.

**Comment by tkcjesse** [comment]
Added new SQM - https://github.com/ArmaLife/Altis/blob/2541f8f04f4be1c57088d1ccdc1a7567b74ccd94/Altis_Life.Altis/mission.sqm#L73
Tested on my server here's my server side RPT - http://pastebin.com/duXu2FkT
