### ISSUE TITLE
Anti-Cheat (Whitelist / Blacklist)

### ISSUE THREAD

**Issue by tkcjesse** [ArmaLife/Altis#468]
This is more of a reminder to myself. I intend to make two sections in some config file to allow server owners to specify the items they want to check against players. Then if the players have those items they get the items removed and flagged probably via diag_log for the time being. Otherwise we can possibly do a kick method once I have time to assemble something using servercommandpassword and such server-side to kick people with the gear defined in the blacklist or not in the whitelist.

If someone has a start they'd like to contribute hit me up or post a pastebin/gitpaste here. :+1:

**Comment by Liam0** [comment]
You could also just use be filters that would make it easier but then again some people dont use them.

**Comment by tkcjesse** [comment]
BE Filters require maintaining through changes. This wouldn't. The current BE filters need a lot of work too.....

**Comment by Kimax89** [comment]
BE Filters are actually really easy to maintain. i use around 5 minutes on each update.
It would be nice if everybody toke the 10 minutes, to just learn how Battleye works.

I use Battleye instead of Spyglass on my server and if people succeed to cheat on my server, they are welcome. But if Battleye catches them, they are banned.

**Comment by tkcjesse** [comment]
@Kimax89 I never said it was difficult. Simply that it requires maintenance through changes. There's plenty of tools out there to even take the lines and condense them and put the \n in for you.

And guys I really don't mean this as a dick, however if you're going to comment saying something is really easy and stuff then contribute the stuff... All I'm doing is offering a simple way to add classnames to an array that will check against players, which is more user friendly in my opinion then having to give people tutorials on how to add BE exceptions.

**Comment by Liam0** [comment]
@tkcjesse i just wanted to give you another option for kick and ban besides i think this is some useless features but thats just my opinion which is probably why i haven't contributed much, Sorry :)

**Comment by tkcjesse** [comment]
@Liam0 And yeah I get that. I mean do you think putting the classnames in a plain-text array in the config would be easier for a newbie or putting them in the appropriate BE filter, with the proper syntax would be easier? I'm genuinely asking this too. If we feel this would be a useless addition then I won't add it.

**Comment by Liam0** [comment]
Array would obviously be easier for a newbie but question is what do u want to accomplish with this. another option could be to change the weapon save to only allow weapons that are added in the config already. Considering people shoulden't have anything that aren't there and maybe change the primary and secondary weapon display in the admin menu to show their entire inventory + virtual items. ofcourse it would be simple to put a restriction into ontake. but either of these still doesn't stop people from spawning it in.

And loops well...

**Comment by tkcjesse** [comment]
No this wouldn't be going into the onTake file, that'd be easy and I considered it and using deleteVehicle _item. It'd be player checks/inventory checks though.

**Comment by Liam0** [comment]
So loop? it was kinda my point im not sure but honestly if you had to check 100 players gear every x amount of minutes well i dont know i wouldent run with it even if u do put it into an already existing loop.

**Comment by Heavybob** [comment]
@tkcjesse I think this is a great idea since most kids have no idea how to use battle eye filters. Might be a good module to include into spyglass.

**Comment by tkcjesse** [comment]
Gonna can this idea for now. Maybe later...
