### ISSUE TITLE
Player Data Logging

### ISSUE THREAD

**Issue by tkcjesse** [ArmaLife/Altis#469]
Since I assume most people don't use a logging .dll or other means of logging like Splunk or other big data processor. I'll work on a means of logging player money transactions and such using diag_logs.

Things to log(feel free to suggest):
- Bank Transactions (ATM Withdrawal / Deposits)
- Player Money Pickups
- Player Money Disconnects
- Player Item Sales
- Player Purchases
- Player Kills

Otherwise if someone else wants to work on it, just post saying you're doing it :+1:

**Comment by Heavybob** [comment]
More logging wouldn't hurt.

**Comment by dardothemaster** [comment]
Is someone working on it? I can take care of the suggestion if no one is actually doing it.

**Comment by tkcjesse** [comment]
I got it.

**Comment by tkcjesse** [comment]
https://github.com/ArmaLife/Altis/pull/494/files

**Comment by tkcjesse** [comment]
Post any issues on the pull request.
