### ISSUE TITLE
Spyglass Debug Spam

### ISSUE THREAD

**Issue by Heavybob** [ArmaLife/Altis#47]
@danielstuart14, Would you kindly help out my friend.

*Running a custom patchlist for spyglass*
17:44:27 Error in expression <Name = _x select 1; if(!(_targetDisplay == 316000)) then { switch(typeName _targ>
17:44:27 Error position: <== 316000)) then {
switch(typeName _targ>
17:44:27 Error Generic error in expression
17:44:27 File mpmissions__CUR_MP.Altis\SpyGlass\fn_menuCheck.sqf, line 32

*Error Code:*
17:44:27 "Variable: life_fnc_adminmarkers_meta is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_admintphere_meta is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_skydive_meta is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_adminfreeze_meta is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_admincompensate is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: connect is not allowed TYPE: SCALAR NS: MN"
17:44:27 "Variable: life_fnc_lockcarsound_meta is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_admingodmode_meta is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_decodeflags is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_modulesiteinit is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_updatevehtrunk is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_lerp is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_egspectatorcameratick is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_twowingdoortwohandleopen is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_getvehiclecustomization is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_god is not allowed TYPE: BOOL NS: MN"
17:44:27 "Variable: life_fnc_adminteleport_meta is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_egobjectivevisualizer is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_admintphere is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_admingodmode is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_egspectatorcameraresettarget is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_admindebugcon is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_egspectatorcamerapreparetarget is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_skydive is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_unlockcarsound is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_admincompensate_meta is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_adminspectate is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_dataterminalanimate is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_egspectator is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_adminspectate_meta is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: ton_fnc_clientgangleft is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: control is not allowed TYPE: SCALAR NS: MN"
17:44:27 "Variable: life_fnc_adminmarkers is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_freezeplayer_meta is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_modulesupportsinitrequester is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_getangledelta is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_egspectatorcamera is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_adminfreeze is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: massi_1 is not allowed TYPE: OBJECT NS: MN"
17:44:27 "Variable: bis_fnc_egspectatorcamerasettarget is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_freezeplayer is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_fnc_usefullinks_meta is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: reb_1_3_1_1 is not allowed TYPE: OBJECT NS: MN"
17:44:27 "Variable: license_civ_ggst1 is not allowed TYPE: BOOL NS: MN"
17:44:27 "Variable: bis_fnc_modulesupportsinitprovider is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: license_civ_ggst2 is not allowed TYPE: BOOL NS: MN"
17:44:27 "Variable: license_civ_ggst3 is not allowed TYPE: BOOL NS: MN"
17:44:27 "Variable: life_inv_rooster is not allowed TYPE: SCALAR NS: MN"
17:44:27 "Variable: bis_fnc_encodeflags is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_egspectatordraw2d is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: life_frozen is not allowed TYPE: BOOL NS: MN"
17:44:27 "Variable: life_markers is not allowed TYPE: BOOL NS: MN"
17:44:27 "Variable: life_fnc_usefullinks is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_egobjectivevisualizerdraw is not allowed TYPE: CODE NS: MN"
17:44:27 "Variable: bis_fnc_getintersectionsundercursor is not allowed TYPE: CODE NS: MN"
17:44:28 Inventory item with given name: [ItemMap] not found
17:44:28 Inventory item with given name: [ItemCompass] not found
17:44:28 Inventory item with given name: [ItemWatch] not found
17:49:37 "Variable: life_fnc_updatevehtrunk_meta is not allowed TYPE: CODE NS: MN"
17:49:37 "Variable: life_fnc_unlockcarsound_meta is not allowed TYPE: CODE NS: MN"
17:49:38 "Variable: bis_taskenhancements_enable is not allowed TYPE: BOOL NS: MN"
17:49:38 "Variable: bis_fnc_modulesupportsinitprovidervirtual is not allowed TYPE: CODE NS: MN"
17:49:38 "Variable: reb_1_4 is not allowed TYPE: OBJECT NS: MN"
17:49:38 "Variable: life_fnc_adminteleport is not allowed TYPE: CODE NS: MN"
17:49:38 "Variable: bis_fnc_dataterminalcolor is not allowed TYPE: CODE NS: MN"
17:49:38 "Variable: diving_npc2 is not allowed TYPE: OBJECT NS: MN"
17:49:38 "Variable: bis_fnc_egspectatordraw3d is not allowed TYPE: CODE NS: MN"
17:49:38 "Variable: life_fnc_lockcarsound is not allowed TYPE: CODE NS: MN"
17:49:38 "Variable: bis_fnc_getobjectbbd is not allowed TYPE: CODE NS: MN"
17:49:38 "Variable: life_fnc_admindebugcon_meta is not allowed TYPE: CODE NS: MN"
17:49:38 "Variable: bis_fnc_twowingdoortwohandleclose is not allowed TYPE: CODE NS: MN"
17:49:38 "Variable: eb_mycursortarget3 is not allowed TYPE: OBJECT NS: MN"
17:49:38 "Variable: myuav is not allowed TYPE: OBJECT NS: MN"
17:49:38 "Variable: eb_mycursortarget4 is not allowed TYPE: OBJECT NS: MN"
17:49:38 "Variable: life_fnc_adminmarkers_meta is not allowed TYPE: CODE NS: MN"
17:49:38 "Variable: life_fnc_admintphere_meta is not allowed TYPE: CODE NS: MN"
17:49:38 "Variable: life_fnc_skydive_meta is not allowed TYPE: CODE NS: MN"
17:49:38 "Variable: life_fnc_adminfreeze_meta is not allowed TYPE: CODE NS: MN"
17:49:38 "Variable: life_fnc_admincompensate is not allowed TYPE: CODE NS: MN"
17:49:38 "Variable: connect is not allowed TYPE: SCALAR NS: MN"
17:49:39 "Variable: life_fnc_lockcarsound_meta is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: life_fnc_admingodmode_meta is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: bis_fnc_decodeflags is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: bis_fnc_modulesiteinit is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: life_fnc_updatevehtrunk is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: bis_fnc_lerp is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: bis_fnc_egspectatorcameratick is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: bis_fnc_twowingdoortwohandleopen is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: bis_fnc_getvehiclecustomization is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: life_god is not allowed TYPE: BOOL NS: MN"
17:49:39 "Variable: life_fnc_adminteleport_meta is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: bis_fnc_egobjectivevisualizer is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: life_fnc_admintphere is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: life_fnc_admingodmode is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: bis_fnc_egspectatorcameraresettarget is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: life_fnc_admindebugcon is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: bis_fnc_egspectatorcamerapreparetarget is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: life_fnc_skydive is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: life_fnc_unlockcarsound is not allowed TYPE: CODE NS: MN"
17:49:39 "Variable: life_fnc_admincompensate_meta is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: life_fnc_adminspectate is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: bis_fnc_dataterminalanimate is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: bis_fnc_egspectator is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: life_fnc_adminspectate_meta is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: ton_fnc_clientgangleft is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: control is not allowed TYPE: SCALAR NS: MN"
17:49:40 "Variable: life_fnc_adminmarkers is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: life_fnc_freezeplayer_meta is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: bis_taskenhancements_3d is not allowed TYPE: BOOL NS: MN"
17:49:40 "Variable: bis_fnc_modulesupportsinitrequester is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: bis_fnc_getangledelta is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: bis_fnc_egspectatorcamera is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: life_fnc_adminfreeze is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: massi_1 is not allowed TYPE: OBJECT NS: MN"
17:49:40 "Variable: bis_fnc_egspectatorcamerasettarget is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: life_fnc_freezeplayer is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: life_fnc_usefullinks_meta is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: reb_1_3_1_1 is not allowed TYPE: OBJECT NS: MN"
17:49:40 "Variable: license_civ_ggst1 is not allowed TYPE: BOOL NS: MN"
17:49:40 "Variable: bis_fnc_modulesupportsinitprovider is not allowed TYPE: CODE NS: MN"
17:49:40 "Variable: license_civ_ggst2 is not allowed TYPE: BOOL NS: MN"
17:49:40 "Variable: license_civ_ggst3 is not allowed TYPE: BOOL NS: MN"
17:49:40 "Variable: life_inv_rooster is not allowed TYPE: SCALAR NS: MN"
17:49:41 "Variable: bis_fnc_encodeflags is not allowed TYPE: CODE NS: MN"
17:49:41 "Variable: bis_fnc_egspectatordraw2d is not allowed TYPE: CODE NS: MN"
17:49:41 "Variable: life_frozen is not allowed TYPE: BOOL NS: MN"
17:49:41 "Variable: life_markers is not allowed TYPE: BOOL NS: MN"
17:49:41 "Variable: life_fnc_usefullinks is not allowed TYPE: CODE NS: MN"
17:49:41 "Variable: bis_fnc_egobjectivevisualizerdraw is not allowed TYPE: CODE NS: MN"
17:49:41 "Variable: bis_fnc_getintersectionsundercursor is not allowed TYPE: CODE NS: MN"
17:54:51 "Variable: life_fnc_updatevehtrunk_meta is not allowed TYPE: CODE NS: MN"
17:54:51 "Variable: life_fnc_unlockcarsound_meta is not allowed TYPE: CODE NS: MN"
17:54:51 "Variable: bis_taskenhancements_enable is not allowed TYPE: BOOL NS: MN"
17:54:51 "Variable: bis_fnc_modulesupportsinitprovidervirtual is not allowed TYPE: CODE NS: MN"
17:54:51 "Variable: reb_1_4 is not allowed TYPE: OBJECT NS: MN"
17:54:51 "Variable: life_fnc_adminteleport is not allowed TYPE: CODE NS: MN"
17:54:51 "Variable: bis_fnc_dataterminalcolor is not allowed TYPE: CODE NS: MN"
17:54:51 "Variable: diving_npc2 is not allowed TYPE: OBJECT NS: MN"
17:54:51 "Variable: bis_fnc_egspectatordraw3d is not allowed TYPE: CODE NS: MN"
17:54:51 "Variable: life_fnc_lockcarsound is not allowed TYPE: CODE NS: MN"
17:54:51 "Variable: bis_fnc_getobjectbbd is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: life_fnc_admindebugcon_meta is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: bis_fnc_twowingdoortwohandleclose is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: eb_mycursortarget3 is not allowed TYPE: OBJECT NS: MN"
17:54:52 "Variable: myuav is not allowed TYPE: OBJECT NS: MN"
17:54:52 "Variable: eb_mycursortarget4 is not allowed TYPE: OBJECT NS: MN"
17:54:52 "Variable: life_fnc_adminmarkers_meta is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: life_fnc_admintphere_meta is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: life_fnc_skydive_meta is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: life_fnc_adminfreeze_meta is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: life_fnc_admincompensate is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: connect is not allowed TYPE: SCALAR NS: MN"
17:54:52 "Variable: life_fnc_lockcarsound_meta is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: life_fnc_admingodmode_meta is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: bis_fnc_decodeflags is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: bis_fnc_modulesiteinit is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: life_fnc_updatevehtrunk is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: bis_fnc_lerp is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: bis_fnc_egspectatorcameratick is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: bis_fnc_twowingdoortwohandleopen is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: bis_fnc_getvehiclecustomization is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: life_god is not allowed TYPE: BOOL NS: MN"
17:54:52 "Variable: life_fnc_adminteleport_meta is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: bis_fnc_egobjectivevisualizer is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: life_fnc_admintphere is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: life_fnc_admingodmode is not allowed TYPE: CODE NS: MN"
17:54:52 "Variable: bis_fnc_egspectatorcameraresettarget is not allowed TYPE: CODE NS: MN"
17:54:53 "Variable: life_fnc_admindebugcon is not allowed TYPE: CODE NS: MN"
17:54:53 "Variable: bis_fnc_egspectatorcamerapreparetarget is not allowed TYPE: CODE NS: MN"
17:54:53 "Variable: life_fnc_skydive is not allowed TYPE: CODE NS: MN"
17:54:53 "Variable: life_fnc_unlockcarsound is not allowed TYPE: CODE NS: MN"
17:54:53 "Variable: life_fnc_admincompensate_meta is not allowed TYPE: CODE NS: MN"
17:54:53 "Variable: life_fnc_adminspectate is not allowed TYPE: CODE NS: MN"
17:54:53 "Variable: bis_fnc_dataterminalanimate is not allowed TYPE: CODE NS: MN"
17:54:53 "Variable: bis_fnc_egspectator is not allowed TYPE: CODE NS: MN"
17:54:53 "Variable: life_fnc_adminspectate_meta is not allowed TYPE: CODE NS: MN"
17:54:53 "Variable: ton_fnc_clientgangleft is not allowed TYPE: CODE NS: MN"
17:54:53 "Variable: control is not allowed TYPE: SCALAR NS: MN"
17:54:53 "Variable: life_fnc_adminmarkers is not allowed TYPE: CODE NS: MN"
17:54:53 "Variable: life_fnc_freezeplayer_meta is not allowed TYPE: CODE NS: MN"
17:54:53 "Variable: bis_taskenhancements_3d is not allowed TYPE: BOOL NS: MN"
17:54:53 "Variable: bis_fnc_modulesupportsinitrequester is not allowed TYPE: CODE NS: MN"
17:54:54 "Variable: bis_fnc_getangledelta is not allowed TYPE: CODE NS: MN"
17:54:54 "Variable: bis_fnc_egspectatorcamera is not allowed TYPE: CODE NS: MN"
17:54:54 "Variable: life_fnc_adminfreeze is not allowed TYPE: CODE NS: MN"
17:54:54 "Variable: massi_1 is not allowed TYPE: OBJECT NS: MN"
17:54:54 "Variable: bis_fnc_egspectatorcamerasettarget is not allowed TYPE: CODE NS: MN"
17:54:54 "Variable: life_fnc_freezeplayer is not allowed TYPE: CODE NS: MN"
17:54:54 "Variable: life_fnc_usefullinks_meta is not allowed TYPE: CODE NS: MN"
17:54:54 "Variable: reb_1_3_1_1 is not allowed TYPE: OBJECT NS: MN"
17:54:54 "Variable: license_civ_ggst1 is not allowed TYPE: BOOL NS: MN"
17:54:54 "Variable: bis_fnc_modulesupportsinitprovider is not allowed TYPE: CODE NS: MN"
17:54:54 "Variable: license_civ_ggst2 is not allowed TYPE: BOOL NS: MN"
17:54:54 "Variable: license_civ_ggst3 is not allowed TYPE: BOOL NS: MN"
17:54:54 "Variable: life_inv_rooster is not allowed TYPE: SCALAR NS: MN"
17:54:54 "Variable: bis_fnc_encodeflags is not allowed TYPE: CODE NS: MN"
17:54:54 "Variable: bis_fnc_egspectatordraw2d is not allowed TYPE: CODE NS: MN"
17:54:54 "Variable: life_frozen is not allowed TYPE: BOOL NS: MN"
17:54:54 "Variable: life_markers is not allowed TYPE: BOOL NS: MN"
17:54:54 "Variable: life_fnc_usefullinks is not allowed TYPE: CODE NS: MN"
17:54:54 "Variable: bis_fnc_egobjectivevisualizerdraw is not allowed TYPE: CODE NS: MN"
17:54:54 "Variable: bis_fnc_getintersectionsundercursor is not allowed TYPE: CODE NS: MN"

**Comment by danielstuart14** [comment]
thx

**Comment by Heavybob** [comment]
This dump does include some of my own small things so if you don't recognize something, it might be something that does not exist in the main build.

**Comment by Heavybob** [comment]
If anyone finds any bugs with having spyglass disabled, please report them.

**Comment by Heavybob** [comment]
Confirmed, Whitelisting is disabled when Spyglass is disabled.
