### ISSUE TITLE
Unsupported Stringtable Format

### ISSUE THREAD

**Issue by DarkSilencerZA** [ArmaLife/Altis#477]
STR_GNOTF_AlreadyControlled

 0:21:55 Unexpected stringtable format inside <Text ID="STR_GNOTF_AlreadyControlled"><Key>
 0:21:55 Unsupported language English in stringtable
 0:21:55 Unexpected stringtable format inside <Text ID="STR_GNOTF_AlreadyControlled"><Key>
 0:21:55 Unsupported language English in stringtable

Not sure if anyone knows about this, but adding it anyways.

**Comment by danielstuart14** [comment]
that's related to arma, not life framework.
