### ISSUE TITLE
DB names do not match.......

### ISSUE THREAD

**Issue by DarkSilencerZA** [ArmaLife/Altis#478]
I would create a pull request for all of this shit but I am 100% noob with Git Shell..

https://github.com/ArmaLife/Altis/blob/master/life_server/config.cpp

https://github.com/ArmaLife/Altis/blob/master/life_hc/config.cpp

https://github.com/ArmaLife/Altis/blob/master/AltisLife.sql

**Comment by danielstuart14** [comment]
that's not the same thing:

How to configure extdb-conf.ini: 
```
[ArmaLife]
Type = MySQL
Name = AltisLife

Username = MyDatabaseLogin
Password = MyDatabasePassword

IP = MyDatabaseIP
Port = 3306
```

**Comment by Liam0** [comment]
i think he means this part
```
CREATE DATABASE IF NOT EXISTS `AltisLife` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `AltisLife`;
```

**Comment by danielstuart14** [comment]
But we use the database "AltisLife"
Just the extDB config is "ArmaLife"

**Comment by danielstuart14** [comment]
```
[ArmaLife] <---- extDB config name
Type = MySQL
Name = AltisLife <----- Database name
```

**Comment by DarkSilencerZA** [comment]
Have you tried launching a server? With your EXACT files, it does not work. I had to modify it, changing both names in the config.cpp, before extDB2 would work.

@danielstuart14

**Comment by DarkSilencerZA** [comment]
My bad..

**Comment by tkcjesse** [comment]
@danielstuart14    Technically shouldn't we use altislife for the DB name in regards to sql being all lowercase anyways?

**Comment by DarkSilencerZA** [comment]
https://github.com/ArmaLife/Altis/commit/977649749d0228eb04fb8d7d952a3604e90eac8f
