### ISSUE TITLE
Windows Key does not work after a player is restrained & escorted..........

### ISSUE THREAD

**Issue by DarkSilencerZA** [ArmaLife/Altis#482]
Restrain a player > Windows Key > Escort

Great... now the player is STUCK since the Windows Key does not work after the player has been escorted.

**Comment by Shield1739** [comment]
Same issue here. I spam the windows key and it randomly pops up for like half a second and disappears

**Comment by fresqo** [comment]
try changing back to cursorTarget in fn_actionKeyHandler.sqf, or what we did is have both _curTarget = cursorTarget;
_curObject = cursorObject; for diff things

**Comment by DarkSilencerZA** [comment]
@danielstuart14

**Comment by HyunsukBaek** [comment]
i have this issue too.

**Comment by tkcjesse** [comment]
Can use http://pastebin.com/k3qy2evW If you guys want for the time being. Just uses cursorTarget for the iskindof Man stuff. Which resolves the problem. You need to make sure you're looking at the person still obviously.

I'm going to offer a modified escorting method that will work better.

**Comment by DarkSilencerZA** [comment]
@Jawshy Is this really a "bug" if we know what the fix is but ignore it anyway. What's the overall plan of using cursorObject? Is there a reason?

**Comment by danielstuart14** [comment]
cursorObject is a newer command that uses less processing and has a better precision.

We should keep away from cursorTarget, and I really recommend using a new escort script then just get back to cursorTarget...

**Comment by DarkSilencerZA** [comment]
@tkcjesse said above that he's working on something so let's see what happens.

**Comment by tkcjesse** [comment]
Yeah. Pretty sure i have a solution. Just need a friend to get on to test it with.

**Comment by Jawshy** [comment]
@DarkSilencerZA, if it isn't working as intended than it's a bug.

**Comment by Kimax89** [comment]
I have made a temporary bugfix for this #513 
But i'm looking into a better solution.

**Comment by tkcjesse** [comment]
Final Fix: https://github.com/ArmaLife/Altis/pull/520
