### ISSUE TITLE
Virtual Toolkits

### ISSUE THREAD

**Issue by tkcjesse** [ArmaLife/Altis#489]
Since a few updates ago. Carrying Toolkits is a huge toll on your fatigue. I'll be submitting a master config option to enable a virtual toolkit.

Dan and I discussed this a long time ago. Just haven't had time till recently now.

**Comment by Heavybob** [comment]
Making them unlimited?

**Comment by danielstuart14** [comment]
just removing the arma Toolkit (that goes to inventory), and replacing with a virtual one.

Same for vehicle toolkit I think...

**Comment by tkcjesse** [comment]
Alright sounds good!

**Comment by danielstuart14** [comment]
we can add an option for setting it unlimited too, since almost all the admins set it as.

**Comment by tkcjesse** [comment]
Ah okay, sounds good. Are you already doing this or no?

**Comment by danielstuart14** [comment]
nop, I'm not.

**Comment by tkcjesse** [comment]
Alright. I got it.

**Comment by tkcjesse** [comment]
https://github.com/ArmaLife/Altis/pull/499 

Please leave any comments on the pull request!
