### ISSUE TITLE
Increase player number support

### ISSUE THREAD

**Issue by Heavybob** [ArmaLife/Altis#492]
Since HC is doing so well in performance, might be a neato idea to increase the supported player amount. Perhaps 120?

**Comment by tkcjesse** [comment]
All you have to do is drop more civilians down and increase max players in description.ext.

**Comment by tkcjesse** [comment]
Plus whether someone can handle this is dependent really on server specifications and connection.

**Comment by danielstuart14** [comment]
for me that's okay, just don't wait me doing it.
If anybody wants to add more units, it's okay. (meds and civ, I think cops are enough for at least 100 civs, idk, as always, I don't play altis since last year)

**Comment by tkcjesse** [comment]
Done. https://github.com/ArmaLife/Altis/pull/500

Tested, not there really was anything to test lol... Post any issues on the pull request please.
