### ISSUE TITLE
cops spawn as a bird

### ISSUE THREAD

**Issue by professormichel** [ArmaLife/Altis#493]
First of all I apologize for my bad english, Dear friends, I would like to congratulate you for the great work with altis life,I really need your help, I downloaded this version of altis life and made some modifications on the map altis on eden editor, only related to buildings, nothing changes in scripts, we edit the buildings only, all the cops spawn as a bird, the civilian and the medic spawn correctly, we are trying to find the problem but we did not get. If necessary, make available the files to simulate and find the problem, I really need your help, I'm sure it must be something very simple to solve, but I broke both my mind that is hard to find the problem yourself.

follow the arma 3 rpt, extdb 
![20160404224724_1](https://cloud.githubusercontent.com/assets/6778297/14269438/20388c64-fabb-11e5-8322-94aaa5f3bb3c.jpg)
![20160404225715_1](https://cloud.githubusercontent.com/assets/6778297/14269439/22ca34e6-fabb-11e5-8c07-0635ffdea35c.jpg)

[LOGS RPT E EXTDB.zip](https://github.com/ArmaLife/Altis/files/203717/LOGS.RPT.E.EXTDB.zip)

**Comment by tkcjesse** [comment]
Are you using: https://github.com/ArmaLife/Altis/commit/e320d714b05d067a0c20e2625c5883271ef9ceb5

**Comment by professormichel** [comment]
In fact, I downloaded today 2 hours ago, the downloaded version was available in this download zip button

**Comment by tkcjesse** [comment]
I just logged in as cop on default repo, respawned and didn't spawn as a bird. It's something you've changed.

**Comment by danielstuart14** [comment]
if you are using an older mission that doesn't have the new mission settings set, then, you'll spawn as a bird.
here: https://github.com/ArmaLife/Altis/commit/b96ca4011afa7389a1eed95c175dedf100d0a418

Also, you should be using the latest server build. (Try to update it)
