### ISSUE TITLE
medics lose food and water, yet there is no shop for them to buy these things

### ISSUE THREAD

**Issue by 9mmfullclip** [ArmaLife/Altis#511]
the mission.sqm shops in armalife do not contain a market (vitem shop for food and water bottles) for the medic faction. however, they are losing food and water in fn_survival. please change either one of them!

**Comment by NiiRoZz** [comment]
It's not possible to fix, it's bis fault

But Thanks you for your report

Cordially : NiiRoZz

**Comment by tkcjesse** [comment]
Market specific to medics added at the hospital npc. 

https://github.com/ArmaLife/Altis/pull/514
