### ISSUE TITLE
Bug progress bar

### ISSUE THREAD

**Issue by BlayfixScott** [ArmaLife/Altis#518]
a progress bar disappears after a few seconds

**Comment by danielstuart14** [comment]
?

**Comment by Jawshy** [comment]
@BlayfixScott, we're going to need more information.

When exactly does this occur? What exactly happens? Are there any errors in any of the RPT logs?

**Comment by tkcjesse** [comment]
He more than likely is running a custom script. For example my status bar operated on cutRsc layer 5 and the progress bar operated on layer 5 as well. I simply changed all my layers for the progress bar to be on layer 3. Fixed my issues with it disappearing.
