### ISSUE TITLE
Issues with medics

### ISSUE THREAD

**Issue by DillGame** [ArmaLife/Altis#523]
I am having issues with medics. When police get revived by medic they get full solider gear in place of what they had.
Second issue occurs when they try to pickup weapons which deletes their medkits.

**Comment by tkcjesse** [comment]
Defibrillators now replace medikits. https://github.com/ArmaLife/Altis/pull/525

**Comment by DarkSilencerZA** [comment]
@tkcjesse I don't think this fixes the issue of the soldier gear, which happens when you get revived by a medic and sometimes when you respawn as well.

On that note, defibs need to have the ability to heal - as medikits did. Otherwise you'll never be able to fully heal a player as a cop or medic which is pointless.

**Comment by tkcjesse** [comment]
I know. The gear thing is a respawn time delay issue i believe. I dont have the problem. Ill look into it. Also, technically a defib would only revive. @danielstuart14 do you want the defib to be usable to heal to 100 or add a virtual item such as a bloodbag or something?

**Comment by tkcjesse** [comment]
Otherwise you have to heal to 100 at the hospital..

**Comment by DarkSilencerZA** [comment]
Most of the issues came in when @danielstuart14 removed certain things from the description.ext. Some things need to stay there from what I can tell.

Yeah bloodbag would be an idea.

**Comment by tkcjesse** [comment]
We'll figure it out together. No big deal.

**Comment by DarkSilencerZA** [comment]
@DillGame Test this https://github.com/ArmaLife/Altis/pull/527

**Comment by DillGame** [comment]
@DarkSilencerZA Now is working. Thanks :)
