### ISSUE TITLE
Still duplication Weapons.

### ISSUE THREAD

**Issue by HyunsukBaek** [ArmaLife/Altis#526]
1. someone is dead and dropped weapons.

2. revives him.

3. there are dropped weapons on the ground and  revived someone has same weapons too.

i don't think about it tested before merged. 
im disappointing

**Comment by tkcjesse** [comment]
Yeah. Verified. I'll take a look into it again.

**Comment by Liam0** [comment]
just do as @danielstuart14 talked about and remove the weapon from saving in fn_fetchDeadGear and fn_loadDeadGear. i dont really have time to do anything right now sorry

**Comment by tkcjesse** [comment]
It should be removed from the ground, because if the cleanup script runs then you're screwed...

**Comment by ToxaBes** [comment]
Guys, I have the same issue started few days ago. I fixed it with next code in "right after death" logic:

```sqf
_lostWeapons = nearestObjects[getPosATL player, ["WeaponHolderSimulated"], 3];
{
     deleteVehicle _x;
} forEach _lostWeapons;
```
hope it help you to fix it too.

**Comment by HyunsukBaek** [comment]
@ToxaBes  thanks!

**Comment by tkcjesse** [comment]
Its funny how we're already using that.

**Comment by tkcjesse** [comment]
@DarkSilencerZA did the respawn delay fix this for you?

**Comment by tkcjesse** [comment]
Pretty sure this is fixed... Anyone? @DarkSilencerZA

**Comment by DarkSilencerZA** [comment]
@tkcjesse Confirmed. RespawnDelay fixed this as well.

**Comment by DarkSilencerZA** [comment]
@HyunsukBaek @ToxaBes https://github.com/ArmaLife/Altis/commit/2af77eb038aeae01ad25becf737bc42ba72f6f02
