### ISSUE TITLE
garage spawn

### ISSUE THREAD

**Issue by numpty9989** [ArmaLife/Altis#535]
having issue where try and get vehicle from garage and freezes on spawning vehicle please wait, doesn't spawn (NO rpt errors client or server side)
https://gyazo.com/0e4d5f346b2a879a0d8a7bbfdbc9ec15 screenshot of spawning

**Comment by Jawshy** [comment]
I could not reproduce this issue using the latest files (https://github.com/ArmaLife/Altis/commit/9c360ef6b7fd0c90997db64d93587ddb1850b580) on the repository and a clean database. 

Make sure your [life_server](https://github.com/ArmaLife/Altis/tree/master/life_server), [mpmissions](https://github.com/ArmaLife/Altis/tree/master/Altis_Life.Altis), and [.sql](https://github.com/ArmaLife/Altis/blob/master/altislife.sql) files are up-to-date with the repository. Let us know if you still have this issue after updating.

**Comment by numpty9989** [comment]
ive just downloaded the latest ones
all stock db connects everything works  so far just that

**Comment by Jawshy** [comment]
Is this happening for all garages or just specific garages?

**Comment by numpty9989** [comment]
All cop civ and medic

**Comment by numpty9989** [comment]
it pulls the garage list perfectly just doesn't spawn them

**Comment by Jawshy** [comment]
Have any changes been made to any of the files?

**Comment by numpty9989** [comment]
no none

**Comment by Jawshy** [comment]
Odd; because, like I said, I couldn't reproduce this issue.

**Comment by numpty9989** [comment]
close this its fixed now was db lagging lol all sorted now

**Comment by Ghostlier** [comment]
how did you fix the problem im stuck :/

**Comment by BoGuu** [comment]
@Ghostlier 

Please use Gitter/Discord/ALRPG forums for help, this isn't the place.

He also mentioned his database was lagging, I would imagine he fixed that.
