### ISSUE TITLE
Issue on Altislife.sql

### ISSUE THREAD

**Issue by Oratorian** [ArmaLife/Altis#547]
Error when inserting the SQl file.

> #1293 - Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

I used the files i downloaded from the Github Repos 

Following Commit . 

> https://github.com/ArmaLife/Altis/commit/a6d2523dbb451a152be7e648fe2083882b52b89d
Mysql Server Version
>Server version: 5.5.47-0ubuntu0.14.04.1 - (Ubuntu)

**Comment by Liam0** [comment]
Which version of MySQL are you using

**Comment by Heavybob** [comment]
Update SQL

**Comment by Oratorian** [comment]
Server version: 5.5.47-0ubuntu0.14.04.1 - (Ubuntu)

**Comment by Liam0** [comment]
Yes ur gonna have to update or adjust altislife.sql and remove line 82

**Comment by Oratorian** [comment]
can i remove the line safely without making the server go crash or bug while trying to insert those values?

**Comment by Liam0** [comment]
it's the lazy way, it shoulden't cause any problems right now but it might down the road. best thing to do is to update.

**Comment by tkcjesse** [comment]
It won't cause any issues...

**Comment by Felix2** [comment]
I've already reported this issue. It's no real fix to upgrade mysql since 90% of ppl use older versions since it come like that with phpmyadmin. 

Somebody should write the sql statement properly instead of ignoring it!

**Comment by Felix2** [comment]
Btw, the fix for this problem is to remove all code after the timestamp on that line.

**Comment by danielstuart14** [comment]
@Felix2 If someone wants to use an older mysql version, just use it. But really, that isn't something I'll think about before merging a new commit.

**Comment by tkcjesse** [comment]
@Felix2   Phpmyadmin shouldn't come with a sql server?? https://www.phpmyadmin.net/
