### ISSUE TITLE
people who have been restrained can enter gunner seat

### ISSUE THREAD

**Issue by 9mmfullclip** [ArmaLife/Altis#551]
https://community.bistudio.com/wiki/allTurrets

from core\cop\fn_restrain.sqf
```
	if(vehicle player == player && life_disable_getOut) then {
		player moveInCargo _vehicle;
	};

	if((vehicle player != player) && life_disable_getOut && (driver (vehicle player) == player)) then {
		player action["eject",vehicle player];
		player moveInCargo _vehicle;
	};
```

This does not account for gunner seats (like HMG hunter where people can switch from cargo to gunner without being ejected or translocated to cargo seat).

**Comment by 9mmfullclip** [comment]
```
	// player must not enter gunner seat when restrained
	// thx to fabiox2011 for finding this!
	if((vehicle player != player) && life_disable_getOut) then {
		if (_vehicle turretUnit [0] == player) then {
			player action["eject",vehicle player];
			player moveInCargo _vehicle;
		};
		
		if (_vehicle turretUnit [1] == player) then {
			player action["eject",vehicle player];
			player moveInCargo _vehicle;
		};
		
		if (_vehicle turretUnit [2] == player) then {
			player action["eject",vehicle player];
			player moveInCargo _vehicle;
		};
		
		if (_vehicle turretUnit [3] == player) then {
			player action["eject",vehicle player];
			player moveInCargo _vehicle;
		};
	};
```

**Comment by 9mmfullclip** [comment]
also restraining people using zipties, escorting people and moving people in and out of cars should not be exclusive to cops on a fair, balanced server. there are a lot of 'security checks' in the code that provide an unfair advantage to cops.

**Comment by 9mmfullclip** [comment]
plus there are flat out bugs where restrained, escorted people have a window of opportunity where the knockout from the civilians passes by (15 seconds) and the cop in this case who got knocked out can happily shoot his gun at people until the restraining kicks in again. this commit contains code that fixes it (the commit is ugly but the piece of code is highlighted in this url):

https://github.com/ALTISLIFERPG-XOREAXEAX-DE/Altis/commit/61e1eb2620d0e9250cc3ad8eaee80761445d3914#diff-b5931eeb1b437982ff7eaf92de63f440R29

**Comment by Liam0** [comment]
i dont know if civilians should be allowed to restrain by default thats a discussion i wont be going into.  
i did noticed some bugs with restrain/knockout giving people time to do weird shit a while back, like restraining while being knocked out. i can't confirm if that's still an issue but i'll check it out along with the moving into gunner seats.

**Comment by 9mmfullclip** [comment]
civilians are allowed to restrain after knocking you out (requires a gun) and using zipties to restrain you.

you can visit me in germany and i show you how it works in real life :)

**Comment by 9mmfullclip** [comment]
also civilians can knock out anybody but not cops in the default altislife, this is something we changed for better balancing because its stupid to believe a cop on duty cannot be knocked out just like any other person in Altis.

**Comment by Liam0** [comment]
@9mmfullclip are you not using the build on this github?

**Comment by Heavybob** [comment]
might think about putting zip ties into master build.

**Comment by Shield1739** [comment]
@Heavybob That would be real noice.

**Comment by Liam0** [comment]
Latest commit should have fixed this
