### ISSUE TITLE
This is more a question then issue

### ISSUE THREAD

**Issue by Oratorian** [ArmaLife/Altis#555]
Please dont harass me for that.

We want to add OPFER as new fraction i found a few Tutos on altisliferpg.com but 4.0 differs from 4.4.

Which files need to be changed to add a new fraction.

Just tell me which files i will manage the rest.

**Comment by tkcjesse** [comment]
4.0 should be extremely similar...  
Put down an east player, then: Search all the files for anything with "east"..

This is not an issue. Your question should be either in the support gitter or @ www.altisliferpg.com

**Comment by Heavybob** [comment]
We could always revert everything we have changed and start again from 4.0. Native Opfor support has been specially included in some parts of the main branch atm and makes it way easier to implement than previous versions.
