### ISSUE TITLE
Toolkit not repairing ** Not a build issue **

### ISSUE THREAD

**Issue by tshowler1** [ArmaLife/Altis#569]
I often use the gitter for help, but now I will start using this.

So I updated most files with the latest build last night,
and for some reason the Toolkit doesn't go virtual, and I cannot repair any vehicles.

Weather or not i've missed a file, I am not 100% sure, but the option to repair the vehicle is there weather or not the vehicle is damaged.

Thought I would chuck it in issues, to see is someone can point me in the right direction.

Also, when I store virtual items(Spike strips, donuts etc) in a vehicle, and store the vehicle the virtual items are no longer there.. The weapons are just not virtual!

Thanks

**Comment by DarkSilencerZA** [comment]
None of this is an issue - it's a problem with your scripts.

**Comment by tshowler1** [comment]
Which is why I posted here, as i am needing the file names that are associated with Toolkits, and virtual items.

**Comment by BoGuu** [comment]
@tshowler1 

See: [this]https://github.com/ArmaLife/Altis/blob/825898977a44a884001fac8dd4412c6488f9fc3b/Altis_Life.Altis/Config_Master.hpp#L27-32)

As for the tool kit. Did you copy all the files to your server, or appended to some already there?

**Comment by tshowler1** [comment]
Thanks BoGuu

I have the toolkit on my person, but cannot use it!
I copied the files I didnt edit them, I'm guessing thats were I went wrong?

I will try give myself Toolkit via admin console, give me 5 min

**Comment by tshowler1** [comment]
I spawned a toolkit it, got a car out, shot out the tyres, tried to repair and nothing

**Comment by BoGuu** [comment]
Does the progress bar appear, can you walk me through it?

I located the problem with the button always being there, will fix that in a moment.

**Comment by tshowler1** [comment]
Ok ill do it in dot formation

- I spawned in at a random spawn point on the spawn screen

- I used infiSTAR to spawn a Toolkit infront of my person.

- I went to the car garage and got a random vehicle out

- I went outside the safezone, to shoot the tyres out

- Tried to use the tool kit to repair the vehicle, but when I press the button nothing happened
No Progress bar, no message..but now the error log wants to update itself, and this is what it shows now


if((life_inv_toolkit >= 1) && (damage _curTa>
 8:06:51   Error position: <life_inv_toolkit >= 1) && (damage _curTa>
 8:06:51   Error Undefined variable in expression: life_inv_toolkit
 8:06:51 File mpmissions\__CUR_MP.Altis\core\vehicle\fn_vInteractionMenu.sqf, line 41
 8:06:52 Error in expression <p") OR (_veh isKindOf "Air")) then {
if(life_inv_toolkit > 0) then {
life_action>
 8:06:52   Error position: <life_inv_toolkit > 0) then {
life_action>

**Comment by BoGuu** [comment]
@tshowler1 

Ok can you try the following:

Replace line 41 [here](https://github.com/ArmaLife/Altis/blob/825898977a44a884001fac8dd4412c6488f9fc3b/Altis_Life.Altis/core/vehicle/fn_vInteractionMenu.sqf#L41)

With:

if((GVAR_MNS "life_inv_toolkit" >= 1) && (damage _curTarget > 0) && alive _curTarget) then {_Btn1 ctrlEnable true;} else {_Btn1 ctrlEnable false;};

**Comment by tshowler1** [comment]
Ok give me another 5 minutes, thank you!

**Comment by BoGuu** [comment]
@tshowler1 

I forgot one last thing before you test it. Replace line 14 [here](https://github.com/ArmaLife/Altis/blob/825898977a44a884001fac8dd4412c6488f9fc3b/Altis_Life.Altis/core/actions/fn_repairTruck.sqf#L14)

With:

if(GVAR_MNS "life_inv_toolkit" > 0) then {

**Comment by tkcjesse** [comment]
Is this an issue with the current build or no? Why are you using mission name space? Has something changed now that i missed?

If this isn't a current build issue you should be getting support in gitter or altisliferpg.com. NOT IN ISSUES ON THE REPO.

**Comment by BoGuu** [comment]
@tkcjesse 

I'm not sure whether his issue is for the current build or not. The mission name space contains the item inventory variables (its a global variable, but I wish to see if it's still undefined).

**Comment by tkcjesse** [comment]
Yeah... it should be working. Anyways. Regardless. This isn't the proper area to be getting support on nonbuild related issues.

**Comment by tshowler1** [comment]
I didn't realise there was updates made, and i had an older build, and updated the required files. Had a few other issues, but will test shortly BoGuu,

@tkcjesse sorry for posting here

**Comment by tshowler1** [comment]
Ok so tested it @BoGuu and now the repair vehicle button doesnt show up at all, and when I first brought a tool kit, it gave me 25 virtual toolkits, and a toolkit in my I inventory!

**Comment by BoGuu** [comment]
@tshowler1 Can you PM me on Gitter?
