### ISSUE TITLE
params

### ISSUE THREAD

**Issue by crackhead** [ArmaLife/Altis#57]
20:16:18 Performance warning: SimpleSerialization::Read 'params' is using type of ,'TEXT' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types

**Comment by tkcjesse** [comment]
https://forums.bistudio.com/topic/181144-update-144-getting-strange-errors-in-rpt/#post2932399

Per Bohemia...

"it's informative warning ... don't panic ;)"
