### ISSUE TITLE
Vehicle Inventory/Trunk

### ISSUE THREAD

**Issue by Heavybob** [ArmaLife/Altis#6]
*REPOST FROM PREVIOUS GIT*
https://github.com/danielstuart14/Altis-Life/issues/24

@Heavybob
I noticed in the database structure that Vehicle Inventory/Trunk does have an inventory collum though in this build its not used. Wondering if it was going to be worked in in the future.

Thanks

**Comment by Heavybob** [comment]
@sargken Mentioned to me during a chat on teampeak that he has created a solution and will commit the change in the coming days.

**Comment by sargken** [comment]
#14 Fixing this issue, #17 Expands on what you are requesting here. Now Gear for Vehicles can be saved.

**Comment by Heavybob** [comment]
https://github.com/ArmaLife/Altis/commit/ef956fb17d62cac7c705c49fd88b315926a21428

Testing pull request later today :+1: @sargken

**Comment by Heavybob** [comment]
*Closing Thread*
