### ISSUE TITLE
Supply system for weapons

### ISSUE THREAD

**Issue by Heavybob** [ArmaLife/Altis#7]
*REPOST FROM PREVIOUS GIT*
https://github.com/danielstuart14/Altis-Life/issues/14

@sargken 
Its a suggestion and u have the knowledge to do it is adding a supply system to gun shops with if you set it to 10 guns if a person buys one there is only 9 left. Possibly also a timer to refresh the supply.

**Comment by NiiRoZz** [comment]
I think it's not for the Official Mission ...
