### ISSUE TITLE
Removal of Admin Menu Button - GET ID

### ISSUE THREAD

**Issue by tkcjesse** [ArmaLife/Altis#81]
So, I've left this annoying waste of a button sit on my menu til just the other day... Then I yanked it. I've never needed it nor understand its purpose in being its own button nonetheless... 

https://github.com/ArmaLife/Altis/blob/master/Altis_Life.Altis/core/admin/fn_admingetID.sqf

Can we remove it?

**Comment by danielstuart14** [comment]
I just read a little, and it's for kicking players using ID instead name or UID.
https://community.bistudio.com/wiki/Multiplayer_Server_Commands

**Comment by tkcjesse** [comment]
mmm. So should it just be kept that way or output to the admin info like the rest of the player info?

**Comment by danielstuart14** [comment]
I think setting it to show up in menu is better than a button. But I won't change it, at least by now.
