### ISSUE TITLE
Possible to roll under the Federal Reserve's large doors

### ISSUE THREAD

**Issue by Jawshy** [ArmaLife/Altis#96]
It is possible to roll under the large doors of **Land_Dome_Big_F** *Dome (Big)*.

###### Steps to reproduce
1. Go to the Federal Reserve. Make sure that the large doors are locked.
2. Go prone parallel to a large door and try to open it while simultaneously rolling into the door.  
3. Sooner or later you should have made it under the door and inside the reserve without having to bolt cut the door. 

Game version: 1.54.133741
Mission version: [4.3](https://github.com/TAWTonic/Altis-Life/releases/tag/v4.3)

**Comment by Heavybob** [comment]
Its possible to volt / jump though any of the wall of the dome. Might be an idea to prevent prone animations / jumping within x distance from fed dome.

**Comment by Heavybob** [comment]
Other solutions that could be done is to just pack in more objects like sandbags but again the first solution is way better.

**Comment by danielstuart14** [comment]
We can still get inside it without jumping. Just get proned and then roll in the ground.

**Comment by danielstuart14** [comment]
Sandbags + no jump in the radius seems to work.

**Comment by danielstuart14** [comment]
Also, we can only enable to unlock vault if all the doors are unlocked

**Comment by Heavybob** [comment]
thats a really good idea dan

**Comment by Heavybob** [comment]
or at least a perimeter door

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis/commit/124ee4487ac8f34b48e97a16f102e7fb7fb03eee
